# Generated by Django 5.2.16 on 2026-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                blank=True, max_length=60, verbose_name="کد رهگیری مرسوله"
            ),
        ),
    ]
