# Generated by Django 5.2.16 on 2026-07-27 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_store_scope_orders_enforce_not_null'),
        ('stores', '0002_create_akhlaghi_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('gateway_code', models.CharField(choices=[('zibal', 'زیبال'), ('cod', 'پرداخت در محل')], max_length=30, verbose_name='کد درگاه')),
                ('display_title', models.CharField(blank=True, help_text='عنوان نمایش\u200cداده\u200cشده در صفحه\u200cی تسویه\u200cحساب (اختیاری — اگر خالی باشد از نام پیش\u200cفرض درگاه استفاده می\u200cشود)', max_length=150, verbose_name='عنوان نمایشی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_sandbox', models.BooleanField(default=False, help_text='فقط برای درگاه\u200cهایی که حالت آزمایشی پشتیبانی می\u200cکنند', verbose_name='حالت آزمایشی (Sandbox)')),
                ('encrypted_credentials', models.TextField(blank=True, default='', help_text='مقدار رمزنگاری\u200cشده — هرگز مستقیم خوانده نمی\u200cشود', verbose_name='اعتبارنامه\u200cی رمزنگاری\u200cشده')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_configs', to='stores.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'پیکربندی درگاه پرداخت',
                'verbose_name_plural': 'پیکربندی\u200cهای درگاه پرداخت',
                'ordering': ['display_order', 'gateway_code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('public_id', models.CharField(editable=False, help_text='شناسه\u200cی غیرترتیبی برای URLها و لاگ\u200cها', max_length=32, unique=True, verbose_name='شناسه\u200cی عمومی')),
                ('amount', models.DecimalField(decimal_places=0, help_text='مبلغ دقیقاً در لحظه\u200cی ایجاد تلاش — تغییرناپذیر', max_digits=14, verbose_name='مبلغ (اسنپ\u200cشات)')),
                ('currency', models.CharField(default='TOMAN', help_text='واحد پولی دقیقاً در لحظه\u200cی ایجاد', max_length=10, verbose_name='واحد پول (اسنپ\u200cشات)')),
                ('status', models.CharField(choices=[('created', 'ایجادشده'), ('requesting', 'در حال درخواست'), ('redirect_ready', 'آماده\u200cی هدایت'), ('pending', 'در انتظار'), ('succeeded', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغوشده'), ('expired', 'منقضی\u200cشده')], default='created', max_length=15, verbose_name='وضعیت')),
                ('gateway_track_id', models.CharField(blank=True, default='', help_text='trackId یا معادل آن از سمت درگاه', max_length=100, verbose_name='شناسه\u200cی پیگیری درگاه')),
                ('gateway_ref_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شماره ارجاع بانکی')),
                ('idempotency_key', models.CharField(blank=True, default='', help_text='برای جلوگیری از ایجاد تلاش\u200cهای تکراری', max_length=64, verbose_name='کلید یکتایی')),
                ('failure_code', models.CharField(blank=True, default='', max_length=50, verbose_name='کد خطا')),
                ('failure_message', models.CharField(blank=True, default='', help_text='پیام امن بدون اطلاعات حساس — قابل نمایش به مدیر', max_length=300, verbose_name='پیام خطا (امن)')),
                ('initiated_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال درخواست')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضا')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.order', verbose_name='سفارش')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='stores.store', verbose_name='فروشگاه')),
                ('gateway_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='orders.paymentgatewayconfig', verbose_name='پیکربندی درگاه')),
            ],
            options={
                'verbose_name': 'تلاش پرداخت',
                'verbose_name_plural': 'تلاش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentgatewayconfig',
            constraint=models.UniqueConstraint(fields=('store', 'gateway_code'), name='uniq_gateway_config_per_store'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['order', '-created_at'], name='idx_attempt_order_date'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['store', 'status'], name='idx_attempt_store_status'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_payment_attempt_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('gateway_track_id', ''), _negated=True), fields=('gateway_track_id',), name='uniq_payment_attempt_track_id'),
        ),
    ]
