# Generated by Django 5.2.16 on 2026-07-29 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("orders", "0006_payment_gateway_config_and_attempt"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ درخواستی"
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        verbose_name="مبلغ تأییدشده",
                    ),
                ),
                (
                    "shipping_refund_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="استردادِ هزینه\u200cی ارسال",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IRT", max_length=8, verbose_name="واحد پول"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "درخواست مشتری"),
                            ("defective_item", "کالای معیوب"),
                            ("wrong_item_shipped", "ارسال کالای اشتباه"),
                            ("order_cancelled", "لغو سفارش"),
                            ("other", "سایر"),
                        ],
                        default="customer_request",
                        max_length=30,
                        verbose_name="علت",
                    ),
                ),
                (
                    "merchant_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت مدیر"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("approved", "تأییدشده"),
                            ("processing", "در حال پردازش"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="pending",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("manual", "دستی (واریز خارج از سیستم)"),
                            ("gateway", "درگاه پرداخت"),
                        ],
                        default="manual",
                        max_length=10,
                        verbose_name="روش استرداد",
                    ),
                ),
                (
                    "gateway_transaction_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="شماره ارجاعِ درگاه",
                    ),
                ),
                (
                    "restock",
                    models.BooleanField(
                        default=False, verbose_name="بازگرداندنِ موجودی"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تکمیل"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, default="", verbose_name="علت شکست"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="کلید یکتای درخواست",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "استرداد",
                "verbose_name_plural": "استردادها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="تعداد")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=14, verbose_name="مبلغ"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_items",
                        to="orders.orderitem",
                        verbose_name="قلمِ سفارش",
                    ),
                ),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.refund",
                        verbose_name="استرداد",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلمِ استرداد",
                "verbose_name_plural": "اقلامِ استرداد",
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "return_number",
                    models.CharField(max_length=24, verbose_name="شماره مرجوعی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "درخواست\u200cشده"),
                            ("under_review", "در حال بررسی"),
                            ("approved", "تأییدشده"),
                            ("rejected", "ردشده"),
                            ("in_transit", "در حال ارسال"),
                            ("received", "دریافت\u200cشده"),
                            ("inspected", "بازرسی\u200cشده"),
                            ("completed", "تکمیل\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="requested",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "انصراف مشتری"),
                            ("defective_item", "کالای معیوب"),
                            ("wrong_item_shipped", "ارسال کالای اشتباه"),
                            ("size_or_fit", "عدم تطابق سایز/اندازه"),
                            ("other", "سایر"),
                        ],
                        default="customer_request",
                        max_length=30,
                        verbose_name="علت",
                    ),
                ),
                (
                    "customer_explanation",
                    models.TextField(
                        blank=True, default="", verbose_name="توضیح مشتری"
                    ),
                ),
                (
                    "merchant_note",
                    models.TextField(
                        blank=True, default="", verbose_name="یادداشت مدیر"
                    ),
                ),
                (
                    "inspection_result",
                    models.TextField(
                        blank=True, default="", verbose_name="نتیجه\u200cی بازرسی"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دریافت"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تکمیل"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="زمان رد"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests_handled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخرین انجام\u200cدهنده",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "refund",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_request",
                        to="orders.refund",
                        verbose_name="استردادِ مرتبط",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_requests",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست مرجوعی",
                "verbose_name_plural": "درخواست\u200cهای مرجوعی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "quantity_requested",
                    models.PositiveIntegerField(verbose_name="تعداد درخواستی"),
                ),
                (
                    "quantity_approved",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد تأییدشده"
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد دریافت\u200cشده"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "نو / بازکردنی نشده"),
                            ("opened", "بازشده، سالم"),
                            ("damaged", "آسیب\u200cدیده"),
                            ("defective", "معیوب"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="وضعیت کالا",
                    ),
                ),
                (
                    "is_restockable",
                    models.BooleanField(
                        default=False, verbose_name="قابل بازگشت به موجودی"
                    ),
                ),
                (
                    "merchant_resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("refund", "استرداد وجه"),
                            ("replace", "تعویض"),
                            ("reject", "رد مرجوعی"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="تصمیمِ مدیر",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="مبلغ استردادیِ این قلم",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", verbose_name="علت رد"),
                ),
                (
                    "restocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان بازگشت به موجودی"
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="orders.orderitem",
                        verbose_name="قلمِ سفارش",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.returnrequest",
                        verbose_name="درخواست مرجوعی",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلمِ مرجوعی",
                "verbose_name_plural": "اقلامِ مرجوعی",
            },
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_amount__gte", 0)),
                name="refund_requested_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("approved_amount__isnull", True),
                    ("approved_amount__gte", 0),
                    _connector="OR",
                ),
                name="refund_approved_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="refund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="uniq_refund_idempotency_key_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="refunditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="refund_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="refunditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="refund_item_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequest",
            constraint=models.UniqueConstraint(
                fields=("store", "return_number"), name="uniq_return_number_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_requested__gt", 0)),
                name="return_item_quantity_requested_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_approved__isnull", True),
                    ("quantity_approved__lte", models.F("quantity_requested")),
                    _connector="OR",
                ),
                name="return_item_approved_lte_requested",
            ),
        ),
        migrations.AddConstraint(
            model_name="returnitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_received__isnull", True),
                    models.Q(
                        ("quantity_approved__isnull", False),
                        ("quantity_received__lte", models.F("quantity_approved")),
                    ),
                    _connector="OR",
                ),
                name="return_item_received_lte_approved",
            ),
        ),
    ]
