# Generated by Django 5.2.16 on 2026-07-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_provision_default_warehouses"),
        ("orders", "0007_refund_refunditem_returnrequest_returnitem_and_more"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingRateRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام قاعده")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اولویت (کوچک\u200cتر = بالاتر)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "min_subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        verbose_name="حداقلِ جمعِ سبد",
                    ),
                ),
                (
                    "max_subtotal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=14,
                        null=True,
                        verbose_name="حداکثرِ جمعِ سبد",
                    ),
                ),
                (
                    "min_weight_grams",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداقلِ وزن (گرم)"
                    ),
                ),
                (
                    "max_weight_grams",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداکثرِ وزن (گرم)"
                    ),
                ),
                (
                    "rate_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مبلغِ نرخ (تومان)",
                    ),
                ),
                (
                    "free_over",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="آستانه\u200cی ارسال رایگانِ این قاعده",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=6, verbose_name="ارز"),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ شروع"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پایان"
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعده\u200cی نرخِ ارسال",
                "verbose_name_plural": "قواعدِ نرخِ ارسال",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام منطقه")),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اولویت (کوچک\u200cتر = بالاتر)"
                    ),
                ),
                (
                    "provinces",
                    models.JSONField(
                        blank=True, default=list, verbose_name="استان\u200cها"
                    ),
                ),
                (
                    "cities",
                    models.JSONField(blank=True, default=list, verbose_name="شهرها"),
                ),
                (
                    "postal_codes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="کدهای پستی"
                    ),
                ),
                (
                    "excluded_provinces",
                    models.JSONField(
                        blank=True, default=list, verbose_name="استان\u200cهای مستثنا"
                    ),
                ),
                (
                    "excluded_cities",
                    models.JSONField(
                        blank=True, default=list, verbose_name="شهرهای مستثنا"
                    ),
                ),
                (
                    "is_fallback",
                    models.BooleanField(
                        default=False, verbose_name="منطقه\u200cی پیش\u200cفرض/ذخیره"
                    ),
                ),
            ],
            options={
                "verbose_name": "منطقه\u200cی ارسال",
                "verbose_name_plural": "مناطقِ ارسال",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="TaxClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیحات"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="پیش\u200cفرض"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cی مالیاتی",
                "verbose_name_plural": "دسته\u200cهای مالیاتی",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="استان"
                    ),
                ),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="نرخ (٪)"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اولویت (کوچک\u200cتر = بالاتر)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "applies_to_shipping",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="اعمال روی ارسال"
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ شروع"
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پایان"
                    ),
                ),
            ],
            options={
                "verbose_name": "نرخِ مالیات",
                "verbose_name_plural": "نرخ\u200cهای مالیات",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="shippingmethod",
            options={
                "ordering": ["display_order", "cost"],
                "verbose_name": "روش ارسال",
                "verbose_name_plural": "روش\u200cهای ارسال",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="is_pickup",
            field=models.BooleanField(
                default=False, verbose_name="تحویلِ حضوری (اسنپ\u200cشات)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="max_delivery_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداکثرِ روزِ تحویل (اسنپ\u200cشات)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="min_delivery_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداقلِ روزِ تحویل (اسنپ\u200cشات)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_address",
            field=models.CharField(
                blank=True,
                default="",
                max_length=300,
                verbose_name="آدرسِ بارگیری (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_warehouse_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="نامِ انبارِ بارگیری (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="prices_include_tax",
            field=models.BooleanField(
                default=False,
                verbose_name="قیمت\u200cها شاملِ مالیات بودند (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="کدِ روشِ ارسال (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_method_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="نامِ روشِ ارسال (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_rate_rule_label",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="برچسبِ قاعده\u200cی نرخ (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_tax",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="مالیاتِ ارسال"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="کدِ منطقه\u200cی ارسال (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zone_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="نامِ منطقه\u200cی ارسال (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rounding_policy",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="سیاستِ گردکردنِ مالیات (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_allocation",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="سهمِ تخفیف از این ردیف",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="fulfillment_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_order_items",
                to="catalog.warehouse",
                verbose_name="انبارِ تأمین\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_class_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=60,
                verbose_name="کدِ دسته\u200cی مالیاتی (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_class_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="نامِ دسته\u200cی مالیاتی (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_rate_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="نرخِ مالیات٪ (اسنپ\u200cشات)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="taxable_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="مبلغِ مشمولِ مالیات",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_tax",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="مجموعِ مالیاتِ این ردیف",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_tax",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=12, verbose_name="مالیاتِ واحد"
            ),
        ),
        migrations.AddField(
            model_name="refund",
            name="shipping_tax_refund_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="استردادِ مالیاتِ ارسال",
            ),
        ),
        migrations.AddField(
            model_name="refunditem",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=14,
                verbose_name="مبلغِ مالیاتِ استردادشده",
            ),
        ),
        migrations.AddField(
            model_name="returnitem",
            name="restock_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_restocks",
                to="catalog.warehouse",
                verbose_name="انبارِ بازگشتِ موجودی",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="cod_eligible",
            field=models.BooleanField(default=False, verbose_name="پرداخت در محل"),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیبِ نمایش"),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="is_pickup",
            field=models.BooleanField(default=False, verbose_name="تحویلِ حضوری"),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="max_delivery_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداکثرِ روزِ تحویل"
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("flat_rate", "نرخ ثابت"),
                    ("free", "رایگان"),
                    ("price_based", "بر اساسِ مبلغ سفارش"),
                    ("weight_based", "بر اساسِ وزن"),
                    ("local_pickup", "تحویل حضوری"),
                ],
                default="flat_rate",
                max_length=20,
                verbose_name="نوعِ روش",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="min_delivery_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="حداقلِ روزِ تحویل"
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="pickup_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickup_shipping_methods",
                to="catalog.warehouse",
                verbose_name="انبارِ بارگیریِ حضوری",
            ),
        ),
        migrations.AddConstraint(
            model_name="refunditem",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)),
                name="refund_item_tax_amount_non_negative",
            ),
        ),
        migrations.AddField(
            model_name="shippingraterule",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rate_rules",
                to="orders.shippingmethod",
                verbose_name="روشِ ارسال",
            ),
        ),
        migrations.AddField(
            model_name="shippingzone",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping_zones",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipping_methods",
                to="orders.shippingzone",
                verbose_name="منطقه\u200cی ارسال",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_delivery_days__isnull", True),
                    ("max_delivery_days__isnull", True),
                    ("min_delivery_days__lte", models.F("max_delivery_days")),
                    _connector="OR",
                ),
                name="shippingmethod_min_lte_max_days",
            ),
        ),
        migrations.AddField(
            model_name="taxclass",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_classes",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tax_rates",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="tax_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="orders.taxclass",
                verbose_name="دسته\u200cی مالیاتی",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingraterule",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate_amount__gte", 0)),
                name="shippingrate_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingraterule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_subtotal__isnull", True),
                    ("max_subtotal__isnull", True),
                    ("min_subtotal__lte", models.F("max_subtotal")),
                    _connector="OR",
                ),
                name="shippingrate_min_lte_max_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingraterule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("min_weight_grams__isnull", True),
                    ("max_weight_grams__isnull", True),
                    ("min_weight_grams__lte", models.F("max_weight_grams")),
                    _connector="OR",
                ),
                name="shippingrate_min_lte_max_weight",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingzone",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_shippingzone_code_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingzone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_fallback", True)),
                fields=("store",),
                name="uniq_fallback_zone_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxclass",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_taxclass_code_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxclass",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("store",),
                name="uniq_default_taxclass_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rate_percent__gte", 0), ("rate_percent__lte", 100)
                ),
                name="taxrate_percent_within_bounds",
            ),
        ),
    ]
