# Generated by Django 5.2.16 on 2026-08-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_productoption_input_type_productvariant_sales_limit"),
        ("orders", "0008_shippingraterule_shippingzone_taxclass_taxrate_and_more"),
        ("stores", "0016_store_integration_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="free_over",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="آستانه\u200cی ارسال رایگان (تومان)",
            ),
        ),
        migrations.AddConstraint(
            model_name="shippingmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__gte", 0)),
                name="shippingmethod_cost_non_negative",
            ),
        ),
    ]
