# Generated by Django 5.2.17 on 2026-08-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0007_cartitem_gift_wrap"),
        ("catalog", "0038_productmetafield"),
        ("customers", "0003_customersegment_customersegmentrule_and_more"),
        ("orders", "0010_orderitem_gift_wrap"),
        ("stores", "0018_storedomain_delivery_readiness"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "-created_at"], name="orders_store_created_idx"
            ),
        ),
    ]
