# Generated by Django 5.2.16 on 2026-07-22 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, unique=True, verbose_name="موبایل"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=80, verbose_name="شهر"),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="مشتری ویژه (VIP)"),
                ),
                (
                    "orders_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد سفارش\u200cها"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="مجموع خرید (تومان)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشتری",
                "verbose_name_plural": "مشتریان",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=150, verbose_name="نام گیرنده"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="موبایل گیرنده"),
                ),
                ("province", models.CharField(max_length=80, verbose_name="استان")),
                ("city", models.CharField(max_length=80, verbose_name="شهر")),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=10, verbose_name="کد پستی"),
                ),
                ("full_address", models.TextField(verbose_name="آدرس پستی کامل")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="آدرس پیش\u200cفرض"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "آدرس",
                "verbose_name_plural": "آدرس\u200cها",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist_items",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "علاقه\u200cمندی",
                "verbose_name_plural": "علاقه\u200cمندی\u200cها",
                "ordering": ["-created_at"],
                "unique_together": {("customer", "product")},
            },
        ),
    ]
