# Generated by Django 5.2.16 on 2026-07-29 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "display_name_override",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="نامِ نمایشیِ اختصاصی",
                    ),
                ),
                (
                    "internal_status",
                    models.CharField(
                        choices=[
                            ("normal", "عادی"),
                            ("vip", "ویژه (VIP)"),
                            ("watch", "تحتِ نظر"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="وضعیتِ داخلی",
                    ),
                ),
                (
                    "internal_notes_summary",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="خلاصه\u200cی یادداشتِ داخلی (سنجاق\u200cشده)",
                    ),
                ),
                (
                    "order_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد سفارش (کش\u200cشده)"
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="مجموع خرید — کش\u200cشده (تومان)",
                    ),
                ),
                (
                    "first_order_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="اولین سفارش"
                    ),
                ),
                (
                    "last_order_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین سفارش"
                    ),
                ),
                (
                    "stats_refreshed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="زمانِ آخرینِ به\u200cروزرسانیِ آمار",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_profiles",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profiles",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایلِ مشتریِ فروشگاه",
                "verbose_name_plural": "پروفایل\u200cهای مشتریِ فروشگاه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="سنجاق\u200cشده"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_notes_authored",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="customers.customerprofile",
                        verbose_name="پروفایلِ مشتری",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشتِ مشتری",
                "verbose_name_plural": "یادداشت\u200cهای مشتری",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام")),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="توضیحات"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, default="", max_length=9, verbose_name="رنگ (Hex)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_tags",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "برچسبِ مشتری",
                "verbose_name_plural": "برچسب\u200cهای مشتری",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="customers.customertag",
                verbose_name="برچسب\u200cها",
            ),
        ),
        migrations.AddConstraint(
            model_name="customertag",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_customertag_code_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="customerprofile",
            constraint=models.UniqueConstraint(
                fields=("store", "customer"), name="uniq_customerprofile_per_store"
            ),
        ),
    ]
