# Generated by Django 5.2.16 on 2026-07-29 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customerprofile_customernote_customertag_and_more"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="توضیحات"
                    ),
                ),
                (
                    "segment_type",
                    models.CharField(
                        choices=[
                            ("static", "دستی (Static)"),
                            ("dynamic", "مبتنی\u200cبر قاعده (Dynamic)"),
                        ],
                        default="static",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "match_mode",
                    models.CharField(
                        choices=[
                            ("all", "همه\u200cی قاعده\u200cها (AND)"),
                            ("any", "هرکدام از قاعده\u200cها (OR)"),
                        ],
                        default="all",
                        max_length=5,
                        verbose_name="حالتِ تطبیق",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ آخرینِ ارزیابی"
                    ),
                ),
                (
                    "last_evaluation_duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="مدتِ آخرینِ ارزیابی (میلی\u200cثانیه)",
                    ),
                ),
                (
                    "last_evaluation_error",
                    models.TextField(
                        blank=True, default="", verbose_name="خطایِ آخرینِ ارزیابی"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_segments",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "سگمنتِ مشتری",
                "verbose_name_plural": "سگمنت\u200cهای مشتری",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSegmentRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("field", models.CharField(max_length=40, verbose_name="فیلد")),
                ("operator", models.CharField(max_length=20, verbose_name="عملگر")),
                (
                    "value",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="مقدار"
                    ),
                ),
                (
                    "value2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="مقدارِ دوم (برایِ between)",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="customers.customersegment",
                        verbose_name="سگمنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "قاعده\u200cیِ سگمنت",
                "verbose_name_plural": "قاعده\u200cهایِ سگمنت",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="CustomerSegmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segment_memberships",
                        to="customers.customer",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="customers.customersegment",
                        verbose_name="سگمنت",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضویتِ سگمنت",
                "verbose_name_plural": "عضویت\u200cهایِ سگمنت",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("segment", "customer"), name="uniq_segment_membership"
                    )
                ],
            },
        ),
    ]
