# Generated by Django 5.2.16 on 2026-08-04 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0017_platform_owner_admin_gap_fill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StorefrontLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "uses_visual_storefront_layout",
                    models.BooleanField(
                        default=False,
                        help_text="تا وقتی این فروشگاه اولین نسخه را منتشر نکرده، صفحه اصلی قدیمی (hard-coded) بدون تغییر رندر می\u200cشود.",
                        verbose_name="استفاده از سازنده بصری",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="storefront_layout",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "چیدمان صفحه فروشگاه",
                "verbose_name_plural": "چیدمان\u200cهای صفحه فروشگاه",
            },
        ),
        migrations.CreateModel(
            name="StorefrontLayoutVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="شماره نسخه"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشرشده"),
                            ("archived", "بایگانی\u200cشده"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "ویرایش دستی"),
                            ("legacy_bootstrap", "برخاسته از صفحه اصلی قدیمی"),
                            ("industry_template", "قالب صنعتی"),
                            ("restored", "بازگردانی از نسخه قبلی"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="منشأ",
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=150, verbose_name="برچسب"),
                ),
                (
                    "header_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پیکربندی هدر"
                    ),
                ),
                (
                    "footer_config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پیکربندی فوتر"
                    ),
                ),
                (
                    "content_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="هش SHA-256 محتوای سریالایز\u200cشده — برای تشخیص drift.",
                        max_length=64,
                        verbose_name="اثر انگشت محتوا",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "layout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="storefront_builder.storefrontlayout",
                        verbose_name="چیدمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخه چیدمان",
                "verbose_name_plural": "نسخه\u200cهای چیدمان",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="storefrontlayout",
            name="draft_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="storefront_builder.storefrontlayoutversion",
                verbose_name="نسخه پیش\u200cنویس",
            ),
        ),
        migrations.AddField(
            model_name="storefrontlayout",
            name="published_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="storefront_builder.storefrontlayoutversion",
                verbose_name="نسخه منتشرشده",
            ),
        ),
        migrations.CreateModel(
            name="StorefrontSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "section_key",
                    models.CharField(max_length=50, verbose_name="نوع بخش"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="تنظیمات"),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="storefront_builder.storefrontlayoutversion",
                        verbose_name="نسخه چیدمان",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش صفحه فروشگاه",
                "verbose_name_plural": "بخش\u200cهای صفحه فروشگاه",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="storefrontlayoutversion",
            constraint=models.UniqueConstraint(
                fields=("layout", "version_number"),
                name="storefront_layout_version_unique_number_per_layout",
            ),
        ),
    ]
