# Generated by Django 5.2.17 on 2026-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront_builder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontsection",
            name="collapsed_in_editor",
            field=models.BooleanField(
                default=False,
                help_text="فقط نمایش فشرده/باز کارت این بخش داخل سازنده بصری را کنترل می\u200cکند — مستقل از is_active؛ هیچ اثری روی نمایش عمومی Storefront ندارد.",
                verbose_name="جمع\u200cشده در ادیتور",
            ),
        ),
    ]
