# Generated by Django 5.2.17 on 2026-08-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront_builder", "0002_storefrontsection_collapsed_in_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontlayoutversion",
            name="appearance_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="قالب/پالت/فونت/گردی/تراکم/حرکت — دقیقاً همان الگویِ header_config/footer_config (JSON روی خودِ نسخه) تا تغییراتِ ظاهری هم از همان چرخه\u200cی Draft/Preview/Publish/Restore عبور کنند، نه یک مسیرِ زنده\u200cی جدا.",
                verbose_name="پیکربندی ظاهر",
            ),
        ),
    ]
