# Generated by Django 5.2.17 on 2026-08-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront_builder", "0011_seed_default_non_home_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontsection",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="بخشِ قفل\u200cشده قابلِ جابه\u200cجایی (بالا/پایین) یا حذف نیست — تا وقتی که ابتدا باز قفل شود (spec §37: «It cannot be moved / It cannot be deleted»). مستقل از is_active (پنهان/نمایان) و duplicable/removable (که نوعِ خودِ section را محدود می\u200cکنند، نه یک نمونه\u200cیِ خاص را).",
                verbose_name="قفل\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="storefrontsection",
            name="row_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phase 1 (معماریِ Universal Block/Data): خالی یعنی این section به\u200cتنهایی و با عرضِ کامل در ردیفِ خودش نمایش داده می\u200cشود — رفتارِ فعلی، بدونِ تغییر. اگر مقدار داشته باشد، این section با دیگر sectionهایی که دقیقاً همین مقدار را دارند (در همان صفحه) در یک «ردیفِ ترکیبی» (Layout Group) قرار می\u200cگیرند — مثلاً پیوستنِ Hero و Instant Offer در یک ردیف با عرض\u200cهای نامساوی. شکلِ این\u200cکه ۲/۳/۴ بلوک واقعاً چطور یک ردیف را می\u200cسازند در ``services/row_service.py`` اعتبارسنجی می\u200cشود، نه اینجا — همان تفکیکِ مسئولیتیِ section_key/SECTION_REGISTRY.",
                max_length=40,
                verbose_name="کلید ردیف",
            ),
        ),
        migrations.AddField(
            model_name="storefrontsection",
            name="row_span",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="فقط وقتی row_key خالی نیست معنا دارد — تعدادِ واحد از ۱۲ واحدِ عرضِ ردیف که این section اشغال می\u200cکند (مثلاً ۴ برای یک\u200cسوم، ۸ برای دو\u200cسوم، ۶ برای نصف). مجموعِ row_span همه\u200cی اعضایِ یک row_key باید دقیقاً ۱۲ شود — ``row_service.validate_page_row_layout`` این را چک می\u200cکند. پیش\u200cفرضِ ۱۲ برایِ sectionهایِ بدونِ row_key (اکثریتِ قریب\u200cبه\u200cاتفاق) بی\u200cاثر است — همیشه «عرضِ کامل» به\u200cهمان\u200cشکلِ امروز باقی می\u200cماند.",
                verbose_name="عرض در ردیف (از ۱۲)",
            ),
        ),
    ]
