# Generated by Django 5.2.17 on 2026-08-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront_builder", "0015_storefrontsection_cell_and_cell_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontlayoutversion",
            name="template_provenance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="U7 — شکلِ ``variant_contract.build_template_provenance`` (کلید/نسخه\u200cیِ Ready Templateای که آخرین\u200cبار روی این Draft اعمال شده — نگاه کنید به ``preset_service.apply_preset``). دیکشنریِ خالی یعنی «هرگز یک Ready Template اعمال نشده» (فروشگاه\u200cهایِ قدیمی/Draftهایِ دستی) — یک حالتِ کاملاً معتبر، نه یک خطا.",
                verbose_name="منشأِ Ready Template",
            ),
        ),
    ]
