# Generated by Django 5.2.17 on 2026-08-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront_builder", "0016_storefrontlayoutversion_template_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontlayoutversion",
            name="template_baseline_snapshot",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Acceptance Batch 2 (post-U11) — عکسِ نرمال\u200cشده و immutable از دقیقاً همان baselineِ Ready Templateای که در لحظه\u200cیِ اعمال، واقعاً روی این Draft نوشته شد (پالتِ پیش\u200cفرض، appearance/header/footerِ نهایی\u200cشده، ترکیبِ هر صفحه با کلیدِ اسلاتِ پایدارِ هر section) — نگاه کنید به ``preset_service.apply_preset``/``build_template_baseline_snapshot``. برخلافِ ``template_provenance`` (فقط کلید/نسخه)، بازنشانی از رویِ این فیلد هرگز به تعریفِ *فعلیِ* Presetِ همان کلید در Registry وابسته نیست — حتی اگر آن تعریفِ پایتونی بعداً (بدونِ افزایشِ نسخه) تغییر کند، این عکس دقیقاً همان چیزی می\u200cماند که مرچنت واقعاً انتخاب کرده بود. دیکشنریِ خالی (پیش\u200cفرض) یعنی «این نسخه هرگز یک Ready Template اعمال\u200cشده ندارد، یا قبل از این Batch ساخته شده و فقط ``template_provenance``یِ قدیمی را دارد» — یک حالتِ کاملاً معتبر و سازگار با گذشته (نگاه کنید به مسیرِ جایگزینِ ``reset_storefront_to_baseline`` برایِ این حالت)، نه یک خطا. هرگز مسیرِ فایلِ renderer را ذخیره نمی\u200cکند — فقط کلیدهایِ پایدارِ Registry و پیکربندیِ نرمال\u200cشده.",
                verbose_name="عکسِ Baselineِ Ready Template",
            ),
        ),
        migrations.AddField(
            model_name="storefrontsection",
            name="template_slot_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Acceptance Batch 2 (post-U11) — هویتِ منطقیِ *جایگاهِ این section درونِ ترکیبِ baselineِ Ready Templateای* که آن را ساخته (نه یک بخشِ منطقیِ خاص مثلِ ``stable_id`` — آن UUID طیِ کلونِ نسخه حفظ می\u200cشود، این کلید هرگز طیِ کلون تغییر نمی\u200cکند اما طیِ Duplicate عمداً *کپی نمی\u200cشود* چون نسخه\u200cیِ تکرارشده دیگر «همان جایگاهِ baseline» نیست). فرمت پایدار و بدونِ وابستگی به Store/مرچنت: ``<template_key>:v<template_version>:<page_type>:<index>``. رشته\u200cی خالی (پیش\u200cفرض) یعنی این section هرگز از یک Ready Template اعمال نشده — یعنی محتوایِ دستیِ مرچنت (بازنشانیِ section/field/component هرگز رویِ آن قابلِ\u200cاجرا نیست، نه اینکه بی\u200cصدا نادیده گرفته شود؛ نگاه کنید به ``preset_service.reset_section_to_baseline``). مستقل از ``order`` — بازچینیِ section توسطِ مرچنت هرگز این کلید را تغییر نمی\u200cدهد، پس بازنشانیِ granular حتی پس از بازچینی/درجِ/حذفِ sectionهایِ دیگر همچنان section درستِ baseline را پیدا می\u200cکند.",
                max_length=160,
                verbose_name="کلیدِ اسلاتِ Baseline",
            ),
        ),
    ]
