# Generated by Django 5.2.17 on 2026-08-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "storefront_builder",
            "0017_add_ready_template_baseline_snapshot_and_slot_key",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="storefrontlayout",
            name="r4_editor_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Feature gate for the R4 storefront-builder editor shell.",
            ),
        ),
        migrations.AddField(
            model_name="storefrontlayoutversion",
            name="edit_revision",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="Monotonic optimistic-concurrency token for Draft mutations.",
            ),
        ),
    ]
