# Generated by Django 5.2.16 on 2026-07-30 08:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        ("subscriptions", "0003_provision_legacy_subscriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreBillingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "legal_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="نام حقوقی/صورتحساب",
                    ),
                ),
                (
                    "billing_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="ایمیلِ صورتحساب",
                    ),
                ),
                (
                    "billing_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="تلفنِ صورتحساب",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="کشور"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="استان"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="شهر"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="کدپستی"
                    ),
                ),
                (
                    "address_line",
                    models.CharField(
                        blank=True, default="", max_length=400, verbose_name="نشانی"
                    ),
                ),
                (
                    "tax_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="شناسه\u200cی مالیاتی",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=8, verbose_name="ارز"),
                ),
                (
                    "locale",
                    models.CharField(
                        default="fa-IR", max_length=12, verbose_name="زبان/محلی"
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_account",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "حسابِ صورتحسابِ فروشگاه",
                "verbose_name_plural": "حساب\u200cهایِ صورتحسابِ فروشگاه",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "plan_code_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="کدِ پلن (اسنپ\u200cشات)",
                    ),
                ),
                (
                    "plan_version_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="اسنپ\u200cشاتِ نسخه\u200cی پلن",
                    ),
                ),
                (
                    "billing_account_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="اسنپ\u200cشاتِ حسابِ صورتحساب",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="شماره\u200cی فاکتور"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("initial", "اولیه"),
                            ("renewal", "تمدید"),
                            ("plan_change", "تغییرِ پلن"),
                            ("manual", "دستی"),
                        ],
                        db_index=True,
                        default="renewal",
                        max_length=12,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("open", "باز (بدهکار)"),
                            ("payment_pending", "در انتظارِ پرداخت"),
                            ("paid", "پرداخت\u200cشده"),
                            ("past_due", "معوق"),
                            ("void", "باطل\u200cشده"),
                            ("uncollectible", "وصول\u200cناشدنی"),
                            ("refunded", "بازپرداخت\u200cشده"),
                            ("partially_refunded", "بازپرداختِ جزئی"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=8, verbose_name="ارز"),
                ),
                (
                    "billing_period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروعِ دوره"
                    ),
                ),
                (
                    "billing_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایانِ دوره"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ صدور"
                    ),
                ),
                (
                    "due_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="زمانِ سررسید",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پرداخت"
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ ابطال"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="جمعِ جزء",
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="جمعِ تخفیف",
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="جمعِ مالیات",
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغِ کل",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغِ پرداخت\u200cشده",
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغِ باقی\u200cمانده",
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="ارجاعِ Provider",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=100,
                        verbose_name="کلیدِ یکتا",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="subscriptions.planversion",
                        verbose_name="نسخه\u200cی پلن",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_invoices",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="subscriptions.storesubscription",
                        verbose_name="اشتراک",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتورِ اشتراک",
                "verbose_name_plural": "فاکتورهایِ اشتراک",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "status"], name="idx_invoice_store_status"
                    ),
                    models.Index(
                        fields=["status", "due_at"], name="idx_invoice_status_due"
                    ),
                    models.Index(
                        fields=["subscription", "status"], name="idx_inv_subscr_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("kind", "renewal")),
                        fields=("subscription", "billing_period_start"),
                        name="uniq_renewal_invoice_per_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("subtotal__gte", 0),
                            ("discount_total__gte", 0),
                            ("tax_total__gte", 0),
                            ("grand_total__gte", 0),
                            ("amount_paid__gte", 0),
                            ("amount_due__gte", 0),
                        ),
                        name="invoice_amounts_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("amount_paid__lte", models.F("grand_total"))
                        ),
                        name="invoice_amount_paid_within_total",
                    ),
                ],
            },
        ),
    ]
