# Generated by Django 5.2.16 on 2026-07-30 08:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=64, unique=True, verbose_name="کلید"),
                ),
                (
                    "last_value",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="آخرین مقدار"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمانِ به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "شمارنده\u200cی صورتحساب",
                "verbose_name_plural": "شمارنده\u200cهایِ صورتحساب",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("plan", "پلن"),
                            ("proration_credit", "اعتبارِ تناسبی"),
                            ("proration_charge", "هزینه\u200cی تناسبی"),
                            ("discount", "تخفیف"),
                            ("tax", "مالیات"),
                            ("manual_adjustment", "تعدیلِ دستی"),
                        ],
                        default="plan",
                        max_length=20,
                        verbose_name="نوعِ ردیف",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="شرح"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1"),
                        max_digits=10,
                        verbose_name="تعداد",
                    ),
                ),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغِ واحد",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="جمعِ جزء",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="تخفیف",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مالیات",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="جمعِ ردیف",
                    ),
                ),
                (
                    "plan_code_snapshot",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="کدِ پلن (اسنپ\u200cشات)",
                    ),
                ),
                (
                    "plan_version_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="اسنپ\u200cشاتِ نسخه\u200cی پلن",
                    ),
                ),
                (
                    "service_period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروعِ دوره\u200cی خدمت"
                    ),
                ),
                (
                    "service_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایانِ دوره\u200cی خدمت"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="billing.subscriptioninvoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "ردیفِ فاکتورِ اشتراک",
                "verbose_name_plural": "ردیف\u200cهایِ فاکتورِ اشتراک",
                "ordering": ["invoice", "id"],
            },
        ),
    ]
