# Generated by Django 5.2.16 on 2026-07-30 08:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_billingsequence_subscriptioninvoiceline"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("provider", models.CharField(max_length=40, verbose_name="Provider")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "ایجادشده"),
                            ("pending", "در انتظار"),
                            ("requires_action", "نیازمندِ اقدام"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                            ("expired", "منقضی\u200cشده"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغ",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=8, verbose_name="ارز"),
                ),
                (
                    "public_token",
                    models.CharField(
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="توکنِ عمومی",
                    ),
                ),
                (
                    "provider_payment_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="شناسه\u200cی پرداختِ Provider",
                    ),
                ),
                (
                    "provider_session_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="شناسه\u200cی جلسه\u200cی Provider",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="کلیدِ یکتا"
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1, verbose_name="شماره\u200cی تلاش"
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="کدِ خطا"
                    ),
                ),
                (
                    "failure_message",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="پیامِ خطا"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ شروع"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پایان"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="billing.subscriptioninvoice",
                        verbose_name="فاکتور",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_payment_attempts",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تلاشِ پرداختِ اشتراک",
                "verbose_name_plural": "تلاش\u200cهایِ پرداختِ اشتراک",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "status"], name="idx_subattempt_inv_status"
                    ),
                    models.Index(
                        fields=["store", "status"], name="idx_subattempt_store_status"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_payment_id", ""), _negated=True),
                        fields=("provider", "provider_payment_id"),
                        name="uniq_provider_payment_id",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="attempt_amount_non_negative",
                    ),
                ],
            },
        ),
    ]
