# Generated by Django 5.2.16 on 2026-07-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_subscriptionpaymentattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("provider", models.CharField(max_length=40, verbose_name="Provider")),
                (
                    "external_event_id",
                    models.CharField(
                        max_length=120, verbose_name="شناسه\u200cی رخدادِ Provider"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="نوعِ رخداد"
                    ),
                ),
                (
                    "signature_valid",
                    models.BooleanField(default=False, verbose_name="امضا معتبر"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("received", "دریافت\u200cشده"),
                            ("processed", "پردازش\u200cشده"),
                            ("failed", "ناموفق"),
                            ("ignored", "نادیده\u200cگرفته\u200cشده"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=12,
                        verbose_name="وضعیتِ پردازش",
                    ),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="هشِ payload",
                    ),
                ),
                (
                    "sanitized_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="payloadِ پاک\u200cسازی\u200cشده",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ دریافت"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پردازش"
                    ),
                ),
                (
                    "error_summary",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="خلاصه\u200cی خطا",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعدادِ Retry"),
                ),
                (
                    "related_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="billing.subscriptioninvoice",
                        verbose_name="فاکتورِ مرتبط",
                    ),
                ),
                (
                    "related_payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="billing.subscriptionpaymentattempt",
                        verbose_name="تلاشِ پرداختِ مرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "رخدادِ Webhookِ صورتحساب",
                "verbose_name_plural": "رخدادهایِ Webhookِ صورتحساب",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["processing_status"], name="idx_webhook_status"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_event_id"),
                        name="uniq_webhook_provider_event",
                    )
                ],
            },
        ),
    ]
