# Generated by Django 5.2.16 on 2026-07-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_billingwebhookevent"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionDunningState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "در جریان"),
                            ("resolved", "حل\u200cشده (پرداخت/باطل)"),
                            ("exhausted", "به پایانِ زمان\u200cبندی رسید"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعدادِ مرحله\u200cی طی\u200cشده"
                    ),
                ),
                (
                    "stage",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مرحله\u200cی زمان\u200cبندی"
                    ),
                ),
                (
                    "next_retry_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="زمانِ Retryِ بعدی",
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ آخرین مرحله"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمانِ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمانِ به\u200cروزرسانی"
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dunning_state",
                        to="billing.subscriptioninvoice",
                        verbose_name="فاکتور",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dunning_states",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "وضعیتِ Dunning",
                "verbose_name_plural": "وضعیت\u200cهایِ Dunning",
            },
        ),
    ]
