# Generated by Django 5.2.16 on 2026-07-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_subscriptiondunningstate"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        ("subscriptions", "0004_alter_subscriptionevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledPlanChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمانِ ایجاد"),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_plan_changes",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_plan_change",
                        to="subscriptions.storesubscription",
                        verbose_name="اشتراک",
                    ),
                ),
                (
                    "target_plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_changes",
                        to="subscriptions.planversion",
                        verbose_name="نسخه\u200cی پلنِ هدف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تغییرِ پلنِ زمان\u200cبندی\u200cشده",
                "verbose_name_plural": "تغییرهایِ پلنِ زمان\u200cبندی\u200cشده",
            },
        ),
    ]
