# Generated by Django 5.2.16 on 2026-07-30 08:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_scheduledplanchange"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionCreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=40,
                        unique=True,
                        verbose_name="شماره\u200cی Credit Note",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("issued", "صادرشده"),
                            ("void", "باطل\u200cشده"),
                        ],
                        db_index=True,
                        default="issued",
                        max_length=8,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="علت"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=8, verbose_name="ارز"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغ",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ صدور"
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ ابطال"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="عامل",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="billing.subscriptioninvoice",
                        verbose_name="فاکتور",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note اشتراک",
                "verbose_name_plural": "Credit Noteهایِ اشتراک",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="Provider"
                    ),
                ),
                (
                    "provider_refund_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="شناسه\u200cی بازپرداختِ Provider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "درخواست\u200cشده"),
                            ("pending", "در انتظار"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="مبلغ",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=8, verbose_name="ارز"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="علت"
                    ),
                ),
                (
                    "failure_code",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="کدِ خطا"
                    ),
                ),
                (
                    "failure_message",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="پیامِ خطا"
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ درخواست"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ تکمیل"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="کلیدِ یکتا"
                    ),
                ),
                (
                    "credit_note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="billing.subscriptioncreditnote",
                        verbose_name="Credit Note",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="billing.subscriptioninvoice",
                        verbose_name="فاکتور",
                    ),
                ),
                (
                    "payment_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="billing.subscriptionpaymentattempt",
                        verbose_name="تلاشِ پرداخت",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="درخواست\u200cدهنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_refunds",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازپرداختِ اشتراک",
                "verbose_name_plural": "بازپرداخت\u200cهایِ اشتراک",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="subscriptioncreditnote",
            index=models.Index(
                fields=["store", "status"], name="idx_creditnote_store_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptioncreditnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="credit_note_amount_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionrefund",
            index=models.Index(
                fields=["store", "status"], name="idx_refund_store_status"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionrefund",
            index=models.Index(
                fields=["invoice", "status"], name="idx_refund_invoice_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionrefund",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="refund_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionrefund",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_refund_id", ""), _negated=True),
                fields=("provider", "provider_refund_id"),
                name="uniq_refund_provider_id",
            ),
        ),
    ]
