# Generated by Django 5.2.16 on 2026-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="checkout_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="کلید تسویه\u200cحساب",
            ),
        ),
    ]
