# Generated by Django 6.0.7 on 2026-07-24 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('body', models.TextField(blank=True, verbose_name='متن صفحه')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='خلاصه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشرشده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('seo_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات SEO')),
                ('show_in_footer', models.BooleanField(default=False, verbose_name='نمایش در فوتر')),
                ('footer_column', models.CharField(blank=True, choices=[('quick_access', 'دسترسی سریع'), ('customer_service', 'خدمات مشتریان')], default='', max_length=20, verbose_name='ستون فوتر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_pages', to=settings.AUTH_USER_MODEL, verbose_name='منتشرکننده')),
            ],
            options={
                'verbose_name': 'صفحه\u200cی محتوایی',
                'verbose_name_plural': 'صفحات محتوایی',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
