# Generated by Django 6.0.7 on 2026-07-24 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_content_page'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contentpage',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), models.Q(('published_at__isnull', False), ('status', 'published')), _connector='OR'), name='content_page_published_requires_timestamp'),
        ),
    ]
