# Generated by Django 6.0.7 on 2026-07-24 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_is_cover_productimage_thumbnail'),
        ('content', '0002_publication_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('destination_type', models.CharField(choices=[('none', 'بدون مقصد'), ('category', 'دسته\u200cبندی'), ('product', 'محصول'), ('brand', 'برند'), ('external', 'لینک خارجی')], default='none', max_length=20, verbose_name='نوع مقصد')),
                ('destination_external_url', models.CharField(blank=True, max_length=500, verbose_name='آدرس لینک خارجی')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('desktop_image', models.ImageField(upload_to='homepage/hero/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, upload_to='homepage/hero/', verbose_name='تصویر موبایل')),
                ('button_label', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('show_button', models.BooleanField(default=False, verbose_name='نمایش دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('destination_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.brand', verbose_name='برند مقصد')),
                ('destination_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='دسته\u200cبندی مقصد')),
                ('destination_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='محصول مقصد')),
            ],
            options={
                'verbose_name': 'اسلاید اصلی',
                'verbose_name_plural': 'اسلایدهای اصلی',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('destination_type', models.CharField(choices=[('none', 'بدون مقصد'), ('category', 'دسته\u200cبندی'), ('product', 'محصول'), ('brand', 'برند'), ('external', 'لینک خارجی')], default='none', max_length=20, verbose_name='نوع مقصد')),
                ('destination_external_url', models.CharField(blank=True, max_length=500, verbose_name='آدرس لینک خارجی')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('desktop_image', models.ImageField(upload_to='homepage/banners/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, upload_to='homepage/banners/', verbose_name='تصویر موبایل')),
                ('button_label', models.CharField(blank=True, max_length=60, verbose_name='متن دکمه')),
                ('show_button', models.BooleanField(default=False, verbose_name='نمایش دکمه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('destination_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.brand', verbose_name='برند مقصد')),
                ('destination_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='دسته\u200cبندی مقصد')),
                ('destination_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='محصول مقصد')),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
