# Generated by Django 6.0.7 on 2026-07-24 07:57

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_homepage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(upload_to='homepage/hero/', validators=[apps.content.models.validate_image_size], verbose_name='تصویر دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='homepage/hero/', validators=[apps.content.models.validate_image_size], verbose_name='تصویر موبایل'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='desktop_image',
            field=models.ImageField(upload_to='homepage/banners/', validators=[apps.content.models.validate_image_size], verbose_name='تصویر دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='homepage/banners/', validators=[apps.content.models.validate_image_size], verbose_name='تصویر موبایل'),
        ),
    ]
