# Generated by Django 6.0.7 on 2026-07-24 08:45

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_image_size_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('platform', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('linkedin', 'لینکدین'), ('x', 'ایکس / توییتر'), ('youtube', 'یوتیوب'), ('aparat', 'آپارات'), ('facebook', 'فیسبوک'), ('custom', 'سفارشی')], default='custom', max_length=20, verbose_name='پلتفرم')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان (برچسب دسترسی\u200cپذیری)')),
                ('url', models.URLField(max_length=500, validators=[apps.content.models.validate_social_url], verbose_name='آدرس')),
                ('icon_name', models.CharField(blank=True, help_text='اگر خالی باشد، آیکون پیش\u200cفرض پلتفرم استفاده می\u200cشود', max_length=30, verbose_name='نام آیکون')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('show_in_header', models.BooleanField(default=False, verbose_name='نمایش در هدر')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='نمایش در فوتر')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه\u200cهای اجتماعی',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
