# Generated by Django 6.0.7 on 2026-07-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_is_cover_productimage_thumbnail'),
        ('content', '0005_social_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان منو')),
                ('location', models.CharField(choices=[('header', 'منوی اصلی'), ('footer_1', 'ستون اول فوتر'), ('footer_2', 'ستون دوم فوتر'), ('footer_3', 'ستون سوم فوتر'), ('mobile', 'منوی موبایل')], max_length=20, unique=True, verbose_name='مکان نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منوها',
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('destination_type', models.CharField(choices=[('none', 'بدون مقصد'), ('category', 'دسته\u200cبندی'), ('product', 'محصول'), ('brand', 'برند'), ('external', 'لینک خارجی')], default='none', max_length=20, verbose_name='نوع مقصد')),
                ('destination_external_url', models.CharField(blank=True, max_length=500, verbose_name='آدرس لینک خارجی')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('destination_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.brand', verbose_name='برند مقصد')),
                ('destination_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='دسته\u200cبندی مقصد')),
                ('destination_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.product', verbose_name='محصول مقصد')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.menu', verbose_name='منو')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='content.menuitem', verbose_name='آیتم والد')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
