# Generated by Django 6.0.7 on 2026-07-24 11:07

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_menu_item_protect_menu_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPaymentLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='footer/payment-logos/', validators=[apps.content.models.validate_image_size], verbose_name='تصویر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'لوگوی پرداخت',
                'verbose_name_plural': 'لوگوهای پرداخت',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('show_branding', models.BooleanField(default=True, verbose_name='نمایش برندینگ')),
                ('show_logo', models.BooleanField(default=True, verbose_name='نمایش لوگو')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات فوتر')),
                ('show_contact', models.BooleanField(default=True, verbose_name='نمایش اطلاعات تماس')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن')),
                ('secondary_phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن ثانویه')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('working_hours', models.CharField(blank=True, max_length=250, verbose_name='ساعات کاری')),
                ('show_navigation', models.BooleanField(default=True, verbose_name='نمایش ناوبری')),
                ('show_social_links', models.BooleanField(default=True, verbose_name='نمایش شبکه\u200cهای اجتماعی')),
                ('show_newsletter', models.BooleanField(default=False, verbose_name='نمایش خبرنامه')),
                ('newsletter_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان خبرنامه')),
                ('newsletter_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح خبرنامه')),
                ('show_trust_badges', models.BooleanField(default=False, verbose_name='نمایش نمادهای اعتماد')),
                ('show_payment_logos', models.BooleanField(default=False, verbose_name='نمایش لوگوهای پرداخت')),
                ('copyright_text', models.CharField(blank=True, max_length=300, verbose_name='متن کپی\u200cرایت')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر',
                'verbose_name_plural': 'تنظیمات فوتر',
            },
        ),
        migrations.CreateModel(
            name='FooterTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='footer/trust-badges/', validators=[apps.content.models.validate_image_size], verbose_name='تصویر')),
                ('destination_url', models.URLField(blank=True, max_length=500, verbose_name='لینک مقصد')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نماد اعتماد',
                'verbose_name_plural': 'نمادهای اعتماد',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
