# Generated by Django 6.0.7 on 2026-07-24 12:03

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_footer_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, validators=[apps.content.models.validate_phone], verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=50, validators=[apps.content.models.validate_phone], verbose_name='تلفن ثانویه'),
        ),
    ]
