# Generated by Django 6.0.7 on 2026-07-24 12:18

import apps.content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_footer_phone_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerpaymentlogo',
            name='image',
            field=models.ImageField(upload_to='footer/payment-logos/', validators=[apps.content.models.validate_image_size, apps.content.models.validate_image_content], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='footertrustbadge',
            name='image',
            field=models.ImageField(upload_to='footer/trust-badges/', validators=[apps.content.models.validate_image_size, apps.content.models.validate_image_content], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='desktop_image',
            field=models.ImageField(upload_to='homepage/hero/', validators=[apps.content.models.validate_image_size, apps.content.models.validate_image_content], verbose_name='تصویر دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='homepage/hero/', validators=[apps.content.models.validate_image_size, apps.content.models.validate_image_content], verbose_name='تصویر موبایل'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='desktop_image',
            field=models.ImageField(upload_to='homepage/banners/', validators=[apps.content.models.validate_image_size, apps.content.models.validate_image_content], verbose_name='تصویر دسکتاپ'),
        ),
        migrations.AlterField(
            model_name='promotionalbanner',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='homepage/banners/', validators=[apps.content.models.validate_image_size, apps.content.models.validate_image_content], verbose_name='تصویر موبایل'),
        ),
    ]
