# Generated by Django 5.2.16 on 2026-07-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0012_backfill_footer_store"),
        ("stores", "0002_create_akhlaghi_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerpaymentlogo",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_payment_logos",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="footersettings",
            name="store",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_settings",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="footertrustbadge",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_trust_badges",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
    ]
