# Generated by Django 5.2.16 on 2026-08-04 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0013_store_scope_settings_enforce_not_null"),
        ("stores", "0017_platform_owner_admin_gap_fill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی رکورد قدیمی که هنوز به هیچ فروشگاهی نسبت داده نشده — در هیچ فروشگاهی نمایش داده نمی\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_pages",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="heroslide",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی رکورد قدیمی که هنوز به هیچ فروشگاهی نسبت داده نشده — در هیچ فروشگاهی نمایش داده نمی\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_slides",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="menu",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی رکورد قدیمی که هنوز به هیچ فروشگاهی نسبت داده نشده — در هیچ فروشگاهی نمایش داده نمی\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menus",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی رکورد قدیمی که هنوز به هیچ فروشگاهی نسبت داده نشده — در هیچ فروشگاهی نمایش داده نمی\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotional_banners",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی رکورد قدیمی که هنوز به هیچ فروشگاهی نسبت داده نشده — در هیچ فروشگاهی نمایش داده نمی\u200cشود.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=220, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="location",
            field=models.CharField(
                choices=[
                    ("header", "منوی اصلی"),
                    ("footer_1", "ستون اول فوتر"),
                    ("footer_2", "ستون دوم فوتر"),
                    ("footer_3", "ستون سوم فوتر"),
                    ("mobile", "منوی موبایل"),
                ],
                max_length=20,
                verbose_name="مکان نمایش",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentpage",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="content_page_unique_slug_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                fields=("store", "location"), name="menu_unique_location_per_store"
            ),
        ),
    ]
