# Generated by Django 5.2.17 on 2026-08-08 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0036_merchantcollection_source_legacy_product_tag"),
        ("content", "0015_assign_legacy_content_ownership"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="destination_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.merchantcollection",
                verbose_name="کالکشن مقصد",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="destination_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.merchantcollection",
                verbose_name="کالکشن مقصد",
            ),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="destination_collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.merchantcollection",
                verbose_name="کالکشن مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
    ]
