# Generated by Django 5.2.17 on 2026-08-08 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0016_add_collection_destination"),
        ("storefront_builder", "0002_storefrontsection_collapsed_in_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="heroslide",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی اسلایدِ سراسریِ فروشگاه (رفتارِ قدیمی، پیش از سازنده بصری) — هر section از نوع hero_banner/image_slider که خودش هیچ اسلایدِ اختصاصی ندارد، همچنان همین اسلایدهای سراسری را نشان می\u200cدهد (سازگاریِ کامل با گذشته). وقتی مرچنت از داخلِ سازنده بصری اسلاید اضافه می\u200cکند، این فیلد به همان section مقداردهی می\u200cشود تا هر نمونه از این section بتواند اسلایدهای مستقلِ خودش را داشته باشد.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hero_slides",
                to="storefront_builder.storefrontsection",
                verbose_name="بخشِ سازنده بصری",
            ),
        ),
        migrations.AddField(
            model_name="promotionalbanner",
            name="section",
            field=models.ForeignKey(
                blank=True,
                help_text="خالی یعنی بنرِ سراسریِ فروشگاه (رفتارِ قدیمی) — هر section از نوع single_banner/multi_banner که خودش هیچ بنرِ اختصاصی ندارد، همچنان همین بنرهای سراسری را نشان می\u200cدهد.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="banners",
                to="storefront_builder.storefrontsection",
                verbose_name="بخشِ سازنده بصری",
            ),
        ),
    ]
