# Generated by Django 5.2.17 on 2026-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0021_backfill_placement_assets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("search", "جستجو"),
                    ("cart", "سبد خرید"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("search", "جستجو"),
                    ("cart", "سبد خرید"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="promotionalbanner",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("search", "جستجو"),
                    ("cart", "سبد خرید"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
        migrations.AlterField(
            model_name="storyrailitem",
            name="destination_type",
            field=models.CharField(
                choices=[
                    ("none", "بدون مقصد"),
                    ("category", "دسته\u200cبندی"),
                    ("product", "محصول"),
                    ("brand", "برند"),
                    ("collection", "کالکشن"),
                    ("search", "جستجو"),
                    ("cart", "سبد خرید"),
                    ("external", "لینک خارجی"),
                ],
                default="none",
                max_length=20,
                verbose_name="نوع مقصد",
            ),
        ),
    ]
