# Generated by Django 5.2.17 on 2026-08-12 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0022_alter_heroslide_destination_type_and_more"),
        ("stores", "0017_platform_owner_admin_gap_fill"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_subscribers",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشترکِ خبرنامه",
                "verbose_name_plural": "مشترکینِ خبرنامه",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "email"),
                        name="newsletter_subscriber_unique_per_store",
                    )
                ],
            },
        ),
    ]
