# Generated by Django 5.2.16 on 2026-07-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "name",
                    models.CharField(
                        default="فروشگاه اینترنتی",
                        max_length=150,
                        verbose_name="نام فروشگاه",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="شعار فروشگاه"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="توضیحات فروشگاه (درباره ما)"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="ایمیل فروشگاه"
                    ),
                ),
                (
                    "contact_address",
                    models.CharField(blank=True, max_length=300, verbose_name="آدرس"),
                ),
                (
                    "tax_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=9,
                        max_digits=5,
                        verbose_name="نرخ مالیات (٪)",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        decimal_places=0,
                        default=500000,
                        max_digits=12,
                        verbose_name="آستانه\u200cی ارسال رایگان (تومان)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات فروشگاه",
                "verbose_name_plural": "تنظیمات فروشگاه",
            },
        ),
    ]
