# Generated by Django 5.2.16 on 2026-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="melipayamak_password",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="رمز عبور ملی\u200cپیامک"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="melipayamak_username",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="نام کاربری ملی\u200cپیامک"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="sms_backend",
            field=models.CharField(
                choices=[
                    ("console", "کنسول (فقط لاگ، برای توسعه)"),
                    ("melipayamak", "ملی\u200cپیامک"),
                ],
                default="console",
                max_length=20,
                verbose_name="درگاه پیامک",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="sms_enabled",
            field=models.BooleanField(
                default=True, verbose_name="فعال\u200cسازی سیستم پیامک"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="sms_sender_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="شماره\u200cی فرستنده"
            ),
        ),
    ]
