# Generated by Django 6.0.7 on 2026-07-23 13:07

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopsettings_melipayamak_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsettings',
            name='accent_color',
            field=models.CharField(default='#FF4D77', max_length=7, validators=[apps.core.models.validate_hex_color], verbose_name='رنگ مکمل'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='shop/branding/', verbose_name='فاوآیکون'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='shop/branding/', verbose_name='لوگوی فروشگاه'),
        ),
        migrations.AddField(
            model_name='shopsettings',
            name='primary_color',
            field=models.CharField(default='#6D28D9', max_length=7, validators=[apps.core.models.validate_hex_color], verbose_name='رنگ اصلی'),
        ),
    ]
