# Generated by Django 5.2.16 on 2026-07-25 05:48

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_visual_identity_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="background_color",
            field=models.CharField(
                default="#F7F5FC",
                max_length=7,
                validators=[apps.core.models.validate_hex_color],
                verbose_name="رنگ پس\u200cزمینه\u200cی صفحه",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="muted_text_color",
            field=models.CharField(
                default="#8B86A3",
                max_length=7,
                validators=[apps.core.models.validate_hex_color],
                verbose_name="رنگ متن کم\u200cرنگ",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="secondary_color",
            field=models.CharField(
                default="#7C3AED",
                max_length=7,
                validators=[apps.core.models.validate_hex_color],
                verbose_name="رنگ ثانویه",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="surface_color",
            field=models.CharField(
                default="#FFFFFF",
                max_length=7,
                validators=[apps.core.models.validate_hex_color],
                verbose_name="رنگ پس\u200cزمینه\u200cی کارت\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="text_color",
            field=models.CharField(
                default="#241C3A",
                max_length=7,
                validators=[apps.core.models.validate_hex_color],
                verbose_name="رنگ متن اصلی",
            ),
        ),
    ]
