# Generated by Django 5.2.16 on 2026-07-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_backfill_shopsettings_store"),
        ("stores", "0002_create_akhlaghi_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopsettings",
            name="store",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_settings",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
    ]
