# Generated by Django 5.2.16 on 2026-07-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_store_scope_settings_enforce_not_null"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_code",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="کد عملیات"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="نوع شیء"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="شناسه\u200cی شیء",
                    ),
                ),
                (
                    "object_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="برچسبِ قابل\u200cخواندنِ شیء",
                    ),
                ),
                (
                    "before_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="خلاصه\u200cی پیش از تغییر"
                    ),
                ),
                (
                    "after_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="خلاصه\u200cی پس از تغییر"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="شناسه\u200cی درخواست/idempotency",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "موفق"), ("failure", "ناموفق")],
                        default="success",
                        max_length=10,
                        verbose_name="نتیجه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_log_entries",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "رخداد حسابرسی",
                "verbose_name_plural": "گزارش رخدادها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "-created_at"], name="idx_audit_store_created"
                    ),
                    models.Index(
                        fields=["store", "action_code", "-created_at"],
                        name="idx_audit_store_action",
                    ),
                ],
            },
        ),
    ]
