# Generated by Django 5.2.16 on 2026-07-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_auditlogentry"),
        ("orders", "0008_shippingraterule_shippingzone_taxclass_taxrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="default_tax_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_for_stores",
                to="orders.taxclass",
                verbose_name="دسته\u200cی مالیاتیِ پیش\u200cفرض",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="prices_include_tax",
            field=models.BooleanField(
                default=False, verbose_name="قیمت\u200cها شاملِ مالیات\u200cاند"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="shipping_taxable",
            field=models.BooleanField(
                default=False, verbose_name="ارسال مشمولِ مالیات است"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="tax_enabled",
            field=models.BooleanField(
                default=True, verbose_name="فعال\u200cسازیِ مالیات"
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="tax_rounding_policy",
            field=models.CharField(
                choices=[
                    ("on_total", "گردکردنِ مجموع"),
                    ("per_line", "گردکردنِ هر ردیف"),
                ],
                default="on_total",
                max_length=20,
                verbose_name="سیاستِ گردکردنِ مالیات",
            ),
        ),
    ]
