# Generated by Django 5.2.16 on 2026-07-29 17:07

import apps.core.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_shopsettings_default_tax_class_and_more"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("products", "کالاها"),
                            ("variants", "تنوع\u200cها"),
                            ("inventory", "موجودیِ انبار"),
                            ("customers", "مشتریان"),
                            ("orders", "سفارش\u200cها"),
                        ],
                        max_length=20,
                        verbose_name="نوع صادرات",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف"),
                            ("processing", "در حالِ پردازش"),
                            ("completed", "تکمیل\u200cشده"),
                            ("failed", "ناموفق"),
                            ("expired", "منقضی\u200cشده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="فیلترهای اعمال\u200cشده"
                    ),
                ),
                (
                    "selected_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="ستون\u200cهای انتخاب\u200cشده",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url=None, location="/home/user/siteSaz3/private_media"
                        ),
                        upload_to=apps.core.models.export_job_upload_path,
                        verbose_name="فایل خروجی",
                    ),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد ردیف"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="پیام خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان شروع پردازش"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="زمان انقضا"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="export_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="درخواست\u200cدهنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_jobs",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست صادرات",
                "verbose_name_plural": "درخواست\u200cهای صادرات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "-created_at"], name="idx_export_store_created"
                    ),
                    models.Index(
                        fields=["store", "status"], name="idx_export_store_status"
                    ),
                ],
            },
        ),
    ]
