# Generated by Django 5.2.16 on 2026-07-29 19:30

import apps.core.models
import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_exportjob"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("products", "کالاها"),
                            ("variants", "تنوع\u200cها"),
                            ("inventory", "موجودیِ انبار"),
                        ],
                        max_length=20,
                        verbose_name="نوعِ واردات",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="نامِ اصلیِ فایل",
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url=None, location="/home/user/siteSaz3/private_media"
                        ),
                        upload_to=apps.core.models.import_job_upload_path,
                        verbose_name="فایلِ منبع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "بارگذاری\u200cشده"),
                            ("validating", "در حالِ اعتبارسنجی"),
                            ("preview_ready", "پیش\u200cنمایش آماده"),
                            ("processing", "در حالِ پردازش"),
                            ("completed", "تکمیل\u200cشده"),
                            ("completed_with_errors", "تکمیل\u200cشده با خطا"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغوشده"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=22,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("create_only", "فقط ایجاد"),
                            ("update_only", "فقط به\u200cروزرسانی"),
                            ("upsert", "ایجاد یا به\u200cروزرسانی (Upsert)"),
                        ],
                        default="upsert",
                        max_length=12,
                        verbose_name="حالتِ اجرا",
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=True, verbose_name="اجرای آزمایشی (Dry Run)"
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="کلیدِ یکتایِ درخواست",
                    ),
                ),
                (
                    "total_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مجموعِ ردیف\u200cها"
                    ),
                ),
                (
                    "valid_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ردیف\u200cهایِ معتبر"
                    ),
                ),
                (
                    "invalid_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ردیف\u200cهایِ نامعتبر"
                    ),
                ),
                (
                    "created_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ردیف\u200cهایِ ایجادشده"
                    ),
                ),
                (
                    "updated_rows",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="ردیف\u200cهایِ به\u200cروزرسانی\u200cشده",
                    ),
                ),
                (
                    "skipped_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ردیف\u200cهایِ ردشده"
                    ),
                ),
                (
                    "failed_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ردیف\u200cهایِ ناموفق"
                    ),
                ),
                (
                    "error_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="خلاصه\u200cی خطا"
                    ),
                ),
                (
                    "error_report_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            base_url=None, location="/home/user/siteSaz3/private_media"
                        ),
                        upload_to=apps.core.models.import_error_report_upload_path,
                        verbose_name="فایلِ گزارشِ خطا",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمانِ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمانِ به\u200cروزرسانی"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ شروعِ پردازش"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پایان"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="درخواست\u200cدهنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواستِ واردات",
                "verbose_name_plural": "درخواست\u200cهایِ واردات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportRowResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.PositiveIntegerField(verbose_name="شماره\u200cی ردیف"),
                ),
                (
                    "source_identifier",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="شناسه\u200cی منبع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "معتبر"),
                            ("invalid", "نامعتبر"),
                            ("created", "ایجادشده"),
                            ("updated", "به\u200cروزرسانی\u200cشده"),
                            ("skipped", "ردشده"),
                            ("failed", "ناموفق"),
                        ],
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "normalized_data_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="خلاصه\u200cی داده\u200cی نرمال\u200cشده",
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="خطاها"),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, verbose_name="هشدارها"),
                ),
                (
                    "target_object_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="نوعِ شیءِ هدف",
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه\u200cی شیءِ هدف"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمانِ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمانِ به\u200cروزرسانی"
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="row_results",
                        to="core.importjob",
                        verbose_name="درخواستِ واردات",
                    ),
                ),
            ],
            options={
                "verbose_name": "نتیجه\u200cی ردیفِ واردات",
                "verbose_name_plural": "نتایجِ ردیف\u200cهایِ واردات",
                "ordering": ["import_job_id", "row_number"],
            },
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["store", "-created_at"], name="idx_import_store_created"
            ),
        ),
        migrations.AddIndex(
            model_name="importjob",
            index=models.Index(
                fields=["store", "status"], name="idx_import_store_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="importjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("store", "idempotency_key"),
                name="uniq_importjob_idempotency_key_per_store",
            ),
        ),
        migrations.AddIndex(
            model_name="importrowresult",
            index=models.Index(
                fields=["import_job", "status"], name="idx_importrow_job_status"
            ),
        ),
        migrations.AddIndex(
            model_name="importrowresult",
            index=models.Index(
                fields=["import_job", "row_number"], name="idx_importrow_job_rownum"
            ),
        ),
        migrations.AddIndex(
            model_name="importrowresult",
            index=models.Index(
                fields=["import_job", "source_identifier"],
                name="idx_importrow_job_srcid",
            ),
        ),
    ]
