# Generated by Django 5.2.16 on 2026-07-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_importjob_importrowresult_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="kavenegar_api_key",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="کلید API کاوه\u200cنگار"
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="sms_backend",
            field=models.CharField(
                choices=[
                    ("console", "کنسول (فقط لاگ، برای توسعه)"),
                    ("melipayamak", "ملی\u200cپیامک"),
                    ("kavenegar", "کاوه\u200cنگار"),
                ],
                default="console",
                max_length=20,
                verbose_name="درگاه پیامک",
            ),
        ),
    ]
