# Generated by Django 5.2.16 on 2026-07-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_shopsettings_kavenegar_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="smsrasti_device_token",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="توکنِ دستگاهِ اسمس\u200cراستی",
            ),
        ),
        migrations.AlterField(
            model_name="shopsettings",
            name="sms_backend",
            field=models.CharField(
                choices=[
                    ("console", "کنسول (فقط لاگ، برای توسعه)"),
                    ("melipayamak", "ملی\u200cپیامک"),
                    ("kavenegar", "کاوه\u200cنگار"),
                    ("smsrasti", "اسمس\u200cراستی (گیت\u200cوی اندروید)"),
                ],
                default="console",
                max_length=20,
                verbose_name="درگاه پیامک",
            ),
        ),
    ]
