# Generated by Django 5.2.16 on 2026-08-02 22:01

import apps.core.models
import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_shopsettings_smsrasti_device_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=255,
                storage=apps.core.storage.PrivateFileSystemStorage(),
                upload_to=apps.core.models.export_job_upload_path,
                verbose_name="فایل خروجی",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="error_report_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                storage=apps.core.storage.PrivateFileSystemStorage(),
                upload_to=apps.core.models.import_error_report_upload_path,
                verbose_name="فایلِ گزارشِ خطا",
            ),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="source_file",
            field=models.FileField(
                blank=True,
                max_length=255,
                storage=apps.core.storage.PrivateFileSystemStorage(),
                upload_to=apps.core.models.import_job_upload_path,
                verbose_name="فایلِ منبع",
            ),
        ),
    ]
