# Generated by Django 5.2.16 on 2026-08-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_private_storage_deconstructible"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="tax_setup_confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="زمانِ تاییدِ صریحِ تنظیماتِ مالیات"
            ),
        ),
    ]
