# Generated by Django 5.2.16 on 2026-07-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("title", models.CharField(max_length=220, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=240,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "category_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="دسته\u200cی نمایشی"
                    ),
                ),
                (
                    "cover_emoji",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="اموجی کاور"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/covers/",
                        verbose_name="تصویر کاور",
                    ),
                ),
                (
                    "tint",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رنگ پس\u200cزمینه"
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(blank=True, max_length=300, verbose_name="خلاصه"),
                ),
                ("body", models.TextField(verbose_name="متن مطلب")),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انتشار"
                    ),
                ),
            ],
            options={
                "verbose_name": "مطلب وبلاگ",
                "verbose_name_plural": "مطالب وبلاگ",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
