# Generated by Django 5.2.16 on 2026-07-29 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EntitlementDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "key",
                    models.SlugField(max_length=60, unique=True, verbose_name="کلید"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=300, verbose_name="توضیحات"
                    ),
                ),
                (
                    "entitlement_type",
                    models.CharField(
                        choices=[
                            ("boolean", "بولی (روشن/خاموش)"),
                            ("integer_limit", "محدودیتِ عددِ صحیح"),
                            ("decimal_limit", "محدودیتِ عددِ اعشاری"),
                            ("text_value", "مقدارِ متنی"),
                        ],
                        default="boolean",
                        max_length=15,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "default_enabled",
                    models.BooleanField(
                        default=False, verbose_name="پیش\u200cفرض: فعال"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "تعریفِ حق\u200cدسترسی",
                "verbose_name_plural": "تعریف\u200cهایِ حق\u200cدسترسی",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="کد")),
                ("name", models.CharField(max_length=100, verbose_name="نامِ داخلی")),
                (
                    "public_title",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="عنوانِ عمومی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_publicly_selectable",
                    models.BooleanField(
                        default=True, verbose_name="قابلِ انتخابِ عمومی"
                    ),
                ),
                (
                    "is_recommended",
                    models.BooleanField(default=False, verbose_name="پیشنهادی"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیبِ نمایش"),
                ),
            ],
            options={
                "verbose_name": "پلن",
                "verbose_name_plural": "پلن\u200cها",
                "ordering": ["display_order", "code"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_publicly_selectable"],
                        name="idx_plan_active_public",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_unlimited",
                    models.BooleanField(default=False, verbose_name="نامحدود"),
                ),
                (
                    "integer_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="محدودیتِ عددی"
                    ),
                ),
                (
                    "decimal_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="محدودیتِ اعشاری",
                    ),
                ),
                (
                    "text_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="مقدارِ متنی",
                    ),
                ),
                (
                    "entitlement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_entitlements",
                        to="subscriptions.entitlementdefinition",
                        verbose_name="حق\u200cدسترسی",
                    ),
                ),
            ],
            options={
                "verbose_name": "حق\u200cدسترسیِ پلن",
                "verbose_name_plural": "حق\u200cدسترسی\u200cهایِ پلن",
                "ordering": ["plan_version", "entitlement__key"],
            },
        ),
        migrations.CreateModel(
            name="PlanVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(verbose_name="شماره\u200cی نسخه"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشرشده"),
                            ("retired", "بازنشسته"),
                            ("archived", "آرشیوشده"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="IRT", max_length=8, verbose_name="ارز"),
                ),
                (
                    "billing_interval",
                    models.CharField(
                        choices=[
                            ("monthly", "ماهانه"),
                            ("yearly", "سالانه"),
                            ("none", "بدونِ دوره (رایگان/legacy)"),
                        ],
                        default="monthly",
                        max_length=10,
                        verbose_name="دوره\u200cی صورتحساب",
                    ),
                ),
                (
                    "display_price",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="قیمتِ نمایشی (اطلاعاتی)",
                    ),
                ),
                (
                    "trial_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="روزهایِ تریال"
                    ),
                ),
                (
                    "grace_period_days",
                    models.PositiveIntegerField(
                        default=7, verbose_name="روزهایِ مهلتِ ارفاقی (grace)"
                    ),
                ),
                (
                    "public_description_snapshot",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="توضیحاتِ عمومی (اسنپ\u200cشات)",
                    ),
                ),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="معتبر از"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ انتشار"
                    ),
                ),
                (
                    "retired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ بازنشستگی"
                    ),
                ),
                (
                    "entitlements",
                    models.ManyToManyField(
                        related_name="plan_versions",
                        through="subscriptions.PlanEntitlement",
                        to="subscriptions.entitlementdefinition",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versions",
                        to="subscriptions.plan",
                        verbose_name="پلن",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخه\u200cی پلن",
                "verbose_name_plural": "نسخه\u200cهایِ پلن",
                "ordering": ["plan", "-version_number"],
            },
        ),
        migrations.AddField(
            model_name="planentitlement",
            name="plan_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_entitlements",
                to="subscriptions.planversion",
                verbose_name="نسخه\u200cی پلن",
            ),
        ),
        migrations.AddIndex(
            model_name="planversion",
            index=models.Index(
                fields=["plan", "status"], name="idx_planversion_plan_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="planversion",
            constraint=models.UniqueConstraint(
                fields=("plan", "version_number"),
                name="uniq_planversion_number_per_plan",
            ),
        ),
        migrations.AddConstraint(
            model_name="planentitlement",
            constraint=models.UniqueConstraint(
                fields=("plan_version", "entitlement"),
                name="uniq_planentitlement_per_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="planentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("integer_limit__isnull", True),
                    ("integer_limit__gte", 0),
                    _connector="OR",
                ),
                name="planentitlement_integer_limit_non_negative",
            ),
        ),
    ]
