# Generated by Django 5.2.16 on 2026-07-30 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("trialing", "دوره\u200cی آزمایشی"),
                            ("active", "فعال"),
                            ("grace_period", "مهلتِ ارفاقی"),
                            ("past_due", "معوق"),
                            ("suspended", "معلق"),
                            ("cancelled", "لغوشده"),
                            ("expired", "منقضی\u200cشده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=14,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="اشتراکِ جاری"),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ شروع"
                    ),
                ),
                (
                    "trial_start_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروعِ تریال"
                    ),
                ),
                (
                    "trial_end_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایانِ تریال"
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروعِ دوره\u200cی جاری"
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایانِ دوره\u200cی جاری"
                    ),
                ),
                (
                    "grace_period_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایانِ مهلتِ ارفاقی"
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False, verbose_name="لغو در پایانِ دوره"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ لغو"
                    ),
                ),
                (
                    "suspended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ تعلیق"
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ انقضا"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("legacy", "مهاجرتِ legacy"),
                            ("default", "پیش\u200cفرضِ فروشگاهِ تازه"),
                            ("admin", "مدیرِ پلتفرم"),
                            ("self_service", "انتخابِ تاجر"),
                        ],
                        default="admin",
                        max_length=15,
                        verbose_name="منبع",
                    ),
                ),
                (
                    "external_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="ارجاعِ خارجی (رزرو برایِ 5B)",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.planversion",
                        verbose_name="نسخه\u200cی پلن",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اشتراکِ فروشگاه",
                "verbose_name_plural": "اشتراک\u200cهایِ فروشگاه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "ایجاد"),
                            ("trial_started", "شروعِ تریال"),
                            ("activated", "فعال\u200cسازی"),
                            ("plan_changed", "تغییرِ پلن"),
                            ("grace_started", "شروعِ مهلتِ ارفاقی"),
                            ("past_due", "معوق\u200cشدن"),
                            ("suspended", "تعلیق"),
                            ("resumed", "ازسرگیری"),
                            ("cancel_scheduled", "زمان\u200cبندیِ لغو"),
                            ("cancelled", "لغو"),
                            ("expired", "انقضا"),
                        ],
                        max_length=20,
                        verbose_name="نوعِ رخداد",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="از وضعیت"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, default="", max_length=14, verbose_name="به وضعیت"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="علت"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="کلیدِ یکتا",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "from_plan_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.planversion",
                        verbose_name="از نسخه\u200cی پلن",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_events",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.storesubscription",
                        verbose_name="اشتراک",
                    ),
                ),
                (
                    "to_plan_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="subscriptions.planversion",
                        verbose_name="به نسخه\u200cی پلن",
                    ),
                ),
            ],
            options={
                "verbose_name": "رخدادِ اشتراک",
                "verbose_name_plural": "رخدادهایِ اشتراک",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "metric_key",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="کلیدِ متریک"
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="شروعِ دوره")),
                ("period_end", models.DateTimeField(verbose_name="پایانِ دوره")),
                (
                    "used_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مقدارِ مصرف\u200cشده"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="subscriptions.storesubscription",
                        verbose_name="اشتراک",
                    ),
                ),
            ],
            options={
                "verbose_name": "رکوردِ مصرف",
                "verbose_name_plural": "رکوردهایِ مصرف",
                "ordering": ["-period_start"],
            },
        ),
        migrations.AddIndex(
            model_name="storesubscription",
            index=models.Index(
                fields=["store", "status"], name="idx_subscription_store_status"
            ),
        ),
        migrations.AddIndex(
            model_name="storesubscription",
            index=models.Index(
                fields=["status", "current_period_end"],
                name="idx_subscription_status_period",
            ),
        ),
        migrations.AddIndex(
            model_name="storesubscription",
            index=models.Index(
                fields=["status", "trial_end_at"], name="idx_subscription_status_trial"
            ),
        ),
        migrations.AddIndex(
            model_name="storesubscription",
            index=models.Index(
                fields=["status", "grace_period_end"],
                name="idx_subscription_status_grace",
            ),
        ),
        migrations.AddConstraint(
            model_name="storesubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("store",),
                name="uniq_current_subscription_per_store",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionevent",
            index=models.Index(
                fields=["store", "-created_at"], name="idx_subevent_store_created"
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionevent",
            index=models.Index(
                fields=["subscription", "-created_at"], name="idx_subevent_sub_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("subscription", "idempotency_key"),
                name="uniq_subscriptionevent_idempotency",
            ),
        ),
        migrations.AddIndex(
            model_name="usagerecord",
            index=models.Index(
                fields=["store", "metric_key", "-period_start"],
                name="idx_usage_store_metric",
            ),
        ),
        migrations.AddConstraint(
            model_name="usagerecord",
            constraint=models.UniqueConstraint(
                fields=("store", "metric_key", "period_start"),
                name="uniq_usagerecord_store_metric_period",
            ),
        ),
    ]
