# Generated by Django 5.2.16 on 2026-07-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_provision_legacy_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "ایجاد"),
                    ("trial_started", "شروعِ تریال"),
                    ("activated", "فعال\u200cسازی"),
                    ("renewed", "تمدید"),
                    ("plan_changed", "تغییرِ پلن"),
                    ("grace_started", "شروعِ مهلتِ ارفاقی"),
                    ("past_due", "معوق\u200cشدن"),
                    ("suspended", "تعلیق"),
                    ("resumed", "ازسرگیری"),
                    ("cancel_scheduled", "زمان\u200cبندیِ لغو"),
                    ("cancelled", "لغو"),
                    ("expired", "انقضا"),
                ],
                max_length=20,
                verbose_name="نوعِ رخداد",
            ),
        ),
    ]
