# Generated by Django 5.2.16 on 2026-07-31 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0013_store_onboarding_stage"),
        ("subscriptions", "0004_alter_subscriptionevent_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("new_subscription", "خریدِ اشتراکِ تازه"),
                            ("upgrade", "ارتقاءِ پلن"),
                            ("renewal", "تمدیدِ اشتراک"),
                        ],
                        max_length=20,
                        verbose_name="علت",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=14,
                        verbose_name="مبلغ (اسنپ\u200cشات)",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="IRT", max_length=8, verbose_name="ارز (اسنپ\u200cشات)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظارِ پرداخت"),
                            ("paid", "پرداخت\u200cشده"),
                            ("void", "باطل\u200cشده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="شناسه\u200cی عمومی",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ پرداخت"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_invoices_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "plan_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_invoices",
                        to="subscriptions.planversion",
                        verbose_name="نسخه\u200cی پلن",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="platform_invoices",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتورِ پلتفرم",
                "verbose_name_plural": "فاکتورهایِ پلتفرم",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformPaymentAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "provider_code",
                    models.CharField(max_length=30, verbose_name="کدِ درگاه"),
                ),
                (
                    "public_id",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="شناسه\u200cی عمومی",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "ایجادشده"),
                            ("pending", "در انتظارِ تأییدِ درگاه"),
                            ("succeeded", "موفق"),
                            ("failed", "ناموفق"),
                        ],
                        default="created",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="ارجاعِ درگاه",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_attempts",
                        to="subscriptions.platforminvoice",
                        verbose_name="فاکتور",
                    ),
                ),
            ],
            options={
                "verbose_name": "تلاشِ پرداختِ پلتفرم",
                "verbose_name_plural": "تلاش\u200cهایِ پرداختِ پلتفرم",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="platforminvoice",
            index=models.Index(
                fields=["store", "-created_at"], name="idx_platform_inv_store"
            ),
        ),
        migrations.AddIndex(
            model_name="platformpaymentattempt",
            index=models.Index(
                fields=["invoice", "-created_at"], name="idx_platform_pay_invoice"
            ),
        ),
    ]
