# Generated by Django 5.2.16 on 2026-07-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_platforminvoice_platformpaymentattempt_and_more"),
    ]

    operations = [
        # PlatformPaymentAttempt (holds the FK to PlatformInvoice) is deleted
        # first, so neither direction of this migration ever needs a
        # separate RemoveField step — Django's autodetector default ordering
        # (RemoveField, then DeleteModel x2) recreates PlatformPaymentAttempt
        # on reverse *before* its "invoice" field/index would be restored by
        # the (also-reversed) RemoveField, so index construction blows up on
        # a field that doesn't exist yet. Deleting the FK-holding model first
        # avoids the split entirely in both directions.
        migrations.DeleteModel(
            name="PlatformPaymentAttempt",
        ),
        migrations.DeleteModel(
            name="PlatformInvoice",
        ),
    ]
