"""
Django settings for shop_core project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from shop_core.env_config import (
    build_database_config,
    env_bool,
    env_int,
    env_list,
    env_str,
    resolve_allowed_hosts,
    resolve_log_level,
    resolve_secret_key,
    resolve_secure_proxy_ssl_header,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Production-sensitive settings are environment-driven — see
# docs/deployment/PRODUCTION_CONFIGURATION.md and .env.example for the full
# variable list. Local development/tests need no environment variables at
# all: every default below preserves the previous hardcoded dev behavior.
# See shop_core/env_config.py for the parsing/validation logic itself
# (kept separate so it can be unit-tested independently of this module).

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret! Raises
# ImproperlyConfigured immediately if DJANGO_DEBUG=False and no real key (or
# the known development-only key) is configured via DJANGO_SECRET_KEY.
SECRET_KEY = resolve_secret_key(DEBUG)

# Raises ImproperlyConfigured if DJANGO_DEBUG=False and DJANGO_ALLOWED_HOSTS
# is not set — production must never silently serve on an unvalidated host.
ALLOWED_HOSTS = resolve_allowed_hosts(DEBUG)

# Comma-separated list of fully-qualified origins (scheme + host) trusted to
# submit cross-origin POSTs, e.g. "https://example.com,https://www.example.com".
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=())

# Gates apps.orders' simulated payment flow (apps/orders/views.py
# payment_start/payment_callback) — there is no real payment gateway yet
# (Zibal integration is a later PR), and payment_callback's "success"/"fail"
# result is a client-controlled URL path segment, so this simulation must
# never be reachable once a deployment is real. Deliberately a SEPARATE flag
# from DEBUG, not `settings.DEBUG` directly: Django's test runner forces
# `settings.DEBUG = False` for the whole test session regardless of this
# file's DEBUG value (see django.test.utils.setup_test_environment), which
# would otherwise silently disable the existing 1500+ checkout/payment tests
# the moment this gate was added. This flag is computed once, at import
# time, from DEBUG's real configured value before any test runner can touch
# it — so it correctly stays enabled for local dev/tests and correctly
# defaults to disabled whenever DJANGO_DEBUG=False is set in the real
# deployment environment (before the process even starts).
PAYMENTS_SIMULATION_ENABLED = env_bool("PAYMENTS_SIMULATION_ENABLED", default=DEBUG)

# Payment credential encryption key — see apps/orders/encryption.py.
# Required in production (DEBUG=False). In development/tests the encryption
# module uses a deterministic dev-only key automatically.
# The _PAYMENT_DEV_KEY_ALLOWED flag tells the encryption module that the dev
# key may be used even when DEBUG is False (Django test runner sets DEBUG=False).
PAYMENT_CREDENTIAL_KEY = env_str("PAYMENT_CREDENTIAL_KEY", "")
_PAYMENT_DEV_KEY_ALLOWED = not PAYMENT_CREDENTIAL_KEY and DEBUG


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core",
    "apps.catalog",
    "apps.customers",
    "apps.cart",
    "apps.orders",
    "apps.dashboard",
    "apps.blog",
    "apps.sms",
    "apps.content",
    "apps.stores",
]

# apps.stores.middleware.StoreResolutionMiddleware runs immediately after
# SecurityMiddleware (Django's own host/security processing) and before
# everything else — in particular, before SessionMiddleware and
# AuthenticationMiddleware, since Store resolution must not depend on, or
# be confused with, session or authentication state. It only reads the
# request's Host header; it never touches request.user or the session.
# See docs/architecture/SAAS_ARCHITECTURE.md ("Request Store Context").
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.stores.middleware.StoreResolutionMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "shop_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.shop_settings",
                "apps.catalog.context_processors.nav_categories",
                "apps.cart.context_processors.cart_badge",
                "apps.customers.context_processors.wishlist_membership",
                "apps.customers.context_processors.auth_forms",
                "apps.content.context_processors.footer_pages",
                "apps.content.context_processors.navigation_menus",
                "apps.content.context_processors.footer_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "shop_core.wsgi.application"


# HTTPS / secure cookies — all disabled by default (matching prior behavior);
# enable via environment once the deployment is reachable over HTTPS
# end-to-end. See docs/deployment/PRODUCTION_CONFIGURATION.md for a staged
# HSTS rollout (HSTS is irreversible-feeling in browsers once accepted, so it
# is never enabled implicitly).
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=False)
SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)

# Unset (None) unless explicitly configured — a reverse proxy's
# X-Forwarded-Proto (or equivalent) header is never trusted by default.
SECURE_PROXY_SSL_HEADER = resolve_secure_proxy_ssl_header()


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# SQLite by default (local dev/tests, unchanged); set DATABASE_URL to a
# postgres:// URL for production. See build_database_config() for validation.

DATABASES = {"default": build_database_config(BASE_DIR)}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fa"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = Path(env_str("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

MEDIA_URL = "media/"
MEDIA_ROOT = Path(env_str("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging — console-only, suitable for a process manager that captures
# stdout/stderr (systemd, gunicorn, a container runtime, etc.). Never logs
# secrets, gateway credentials, OTP codes, full customer PII, or session
# tokens — existing call sites (e.g. apps/sms) already avoid this; this
# config does not add anything that would start doing so.
#
# "payment" is a reserved logger namespace for the future Zibal integration
# (see docs/00_PROJECT_MASTER_REFERENCE.md) — payment code should log via
# logging.getLogger("payment") once written, and will inherit this config
# automatically without further changes here.
LOG_LEVEL = resolve_log_level()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "payment": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Business defaults (Stage 2 will read these in the pricing service)
SHOP_FREE_SHIPPING_THRESHOLD = 500_000
SHOP_TAX_PERCENT = 9

# هویت عمومی پلتفرم (نه یک فروشنده‌ی خاص) — مطابق اصل جنریک‌بودن سند مشخصات
SHOP_NAME = "دیجی‌مارکت"
SHOP_TAGLINE = "فروشگاه اینترنتی چندمنظوره"
SHOP_CONTACT_PHONE = "021-91008877"
SHOP_CONTACT_EMAIL = "info@digimarket.ir"
SHOP_CONTACT_ADDRESS = "تهران، خیابان ولیعصر"
