"""
Django settings for shop_core project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from shop_core.env_config import (
    build_database_config,
    env_bool,
    env_int,
    env_list,
    env_str,
    resolve_allowed_hosts,
    resolve_log_level,
    resolve_secret_key,
    resolve_secure_proxy_ssl_header,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Production-sensitive settings are environment-driven — see
# docs/deployment/PRODUCTION_CONFIGURATION.md and .env.example for the full
# variable list. Local development/tests need no environment variables at
# all: every default below preserves the previous hardcoded dev behavior.
# See shop_core/env_config.py for the parsing/validation logic itself
# (kept separate so it can be unit-tested independently of this module).

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret! Raises
# ImproperlyConfigured immediately if DJANGO_DEBUG=False and no real key (or
# the known development-only key) is configured via DJANGO_SECRET_KEY.
SECRET_KEY = resolve_secret_key(DEBUG)

# Raises ImproperlyConfigured if DJANGO_DEBUG=False and DJANGO_ALLOWED_HOSTS
# is not set — production must never silently serve on an unvalidated host.
ALLOWED_HOSTS = resolve_allowed_hosts(DEBUG)
if DEBUG:
    # Local-dev-only wildcard for the platform's own hosts (marketing/portal
    # at rastisi.localhost, platform admin at platformadmins.rastisi.localhost,
    # trial/claimed storefronts at <label>.rastisi.localhost, merchant admin
    # at <admin_subdomain>.rastisi.localhost). Django's leading-dot ALLOWED_
    # HOSTS syntax matches the bare domain too, so this one entry covers all
    # of them. Production must set the real ".rastisi.ir" wildcard (or exact
    # hosts) via DJANGO_ALLOWED_HOSTS — never hardcoded here (see
    # resolve_allowed_hosts above, which already requires it when DEBUG=False).
    #
    # Also re-states Django's own implicit "DEBUG=True + empty ALLOWED_HOSTS
    # allows localhost/127.0.0.1/[::1]" behavior explicitly: that implicit
    # rule only fires when ALLOWED_HOSTS is *empty*, and this block makes it
    # non-empty, which would otherwise silently break every existing test/
    # dev flow that hits a bare "localhost" Host (e.g.
    # apps/stores/tests/test_middleware.py) the moment this setting was added.
    ALLOWED_HOSTS = list(ALLOWED_HOSTS) + ["localhost", "127.0.0.1", "[::1]", ".rastisi.localhost"]

# Comma-separated list of fully-qualified origins (scheme + host) trusted to
# submit cross-origin POSTs, e.g. "https://example.com,https://www.example.com".
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=())

# Gates apps.orders' simulated payment flow (apps/orders/views.py
# payment_start/payment_callback) — there is no real payment gateway yet
# (Zibal integration is a later PR), and payment_callback's "success"/"fail"
# result is a client-controlled URL path segment, so this simulation must
# never be reachable once a deployment is real. Deliberately a SEPARATE flag
# from DEBUG, not `settings.DEBUG` directly: Django's test runner forces
# `settings.DEBUG = False` for the whole test session regardless of this
# file's DEBUG value (see django.test.utils.setup_test_environment), which
# would otherwise silently disable the existing 1500+ checkout/payment tests
# the moment this gate was added. This flag is computed once, at import
# time, from DEBUG's real configured value before any test runner can touch
# it — so it correctly stays enabled for local dev/tests and correctly
# defaults to disabled whenever DJANGO_DEBUG=False is set in the real
# deployment environment (before the process even starts).
PAYMENTS_SIMULATION_ENABLED = env_bool("PAYMENTS_SIMULATION_ENABLED", default=DEBUG)

# Payment credential encryption key — see apps/orders/encryption.py.
# Required in production (DEBUG=False). In development/tests the encryption
# module uses a deterministic dev-only key automatically.
# The _PAYMENT_DEV_KEY_ALLOWED flag tells the encryption module that the dev
# key may be used even when DEBUG is False (Django test runner sets DEBUG=False).
PAYMENT_CREDENTIAL_KEY = env_str("PAYMENT_CREDENTIAL_KEY", "")
_PAYMENT_DEV_KEY_ALLOWED = not PAYMENT_CREDENTIAL_KEY and DEBUG


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core",
    "apps.catalog",
    "apps.customers",
    "apps.cart",
    "apps.orders",
    "apps.dashboard",
    "apps.blog",
    "apps.sms",
    "apps.content",
    "apps.stores",
    "apps.subscriptions",
    "apps.billing",
    "apps.portal",
    "apps.notifications",
]

# apps.stores.middleware.StoreResolutionMiddleware runs immediately after
# SecurityMiddleware (Django's own host/security processing) and before
# everything else — in particular, before SessionMiddleware and
# AuthenticationMiddleware, since Store resolution must not depend on, or
# be confused with, session or authentication state. It only reads the
# request's Host header; it never touches request.user or the session.
# See docs/architecture/SAAS_ARCHITECTURE.md ("Request Store Context").
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "apps.stores.middleware.StoreResolutionMiddleware",
    # Routes Rastisi's own platform-level hosts (bare marketing/owner-portal
    # host, and the separate platform-admin host) to a dedicated URLconf via
    # request.urlconf — additive, never touches request.store or any
    # per-Store routing decision (ADR-97). Must run after StoreResolution-
    # Middleware (so request.store is already set, even if None on these
    # hosts) and before anything that dispatches on request.urlconf.
    "apps.portal.middleware.PlatformHostRoutingMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "shop_core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.shop_settings",
                "apps.catalog.context_processors.nav_categories",
                "apps.cart.context_processors.cart_badge",
                "apps.customers.context_processors.wishlist_membership",
                "apps.customers.context_processors.auth_forms",
                "apps.content.context_processors.footer_pages",
                "apps.content.context_processors.navigation_menus",
                "apps.content.context_processors.footer_settings",
                "apps.dashboard.context_processors.merchant_permissions",
                "apps.dashboard.context_processors.subscription_banner",
                "apps.dashboard.context_processors.platform_link",
            ],
        },
    },
]

WSGI_APPLICATION = "shop_core.wsgi.application"


# HTTPS / secure cookies — all disabled by default (matching prior behavior);
# enable via environment once the deployment is reachable over HTTPS
# end-to-end. See docs/deployment/PRODUCTION_CONFIGURATION.md for a staged
# HSTS rollout (HSTS is irreversible-feeling in browsers once accepted, so it
# is never enabled implicitly).
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=False)
SECURE_HSTS_SECONDS = env_int("DJANGO_SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)

# Unset (None) unless explicitly configured — a reverse proxy's
# X-Forwarded-Proto (or equivalent) header is never trusted by default.
SECURE_PROXY_SSL_HEADER = resolve_secure_proxy_ssl_header()

# "Remember me" session duration (unified login — every interactive login
# form). Applied via apps.portal.services.session_service.apply_remember_me,
# never hand-rolled per view. Unchecked = 0 (expire when the browser
# closes, Django's SESSION_EXPIRE_AT_BROWSER_CLOSE semantics); checked = a
# real persistent duration. Both are plain integers (seconds) so there is
# exactly one place either is configured, not one per view.
AUTH_SESSION_DEFAULT_EXPIRY_SECONDS = env_int("AUTH_SESSION_DEFAULT_EXPIRY_SECONDS", default=0)
AUTH_SESSION_REMEMBER_ME_EXPIRY_SECONDS = env_int(
    "AUTH_SESSION_REMEMBER_ME_EXPIRY_SECONDS", default=60 * 60 * 24 * 30,
)


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# SQLite by default (local dev/tests, unchanged); set DATABASE_URL to a
# postgres:// URL for production. See build_database_config() for validation.

DATABASES = {"default": build_database_config(BASE_DIR)}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fa"

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = Path(env_str("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

MEDIA_URL = "media/"
MEDIA_ROOT = Path(env_str("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

# Private storage for generated export files and uploaded import source
# files (Admin Panel Completion Program checkpoint 4, ADR-52) — deliberately
# NOT under MEDIA_ROOT/MEDIA_URL, so nothing here is ever reachable through
# Django's ordinary public media serving. Every read of a file in this
# directory must go through an authenticated, Store-scoped dashboard view
# (``apps.core.services.export_service``/``import_service`` download views),
# never a direct URL.
PRIVATE_MEDIA_ROOT = Path(env_str("DJANGO_PRIVATE_MEDIA_ROOT", str(BASE_DIR / "private_media")))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Logging — console-only, suitable for a process manager that captures
# stdout/stderr (systemd, gunicorn, a container runtime, etc.). Never logs
# secrets, gateway credentials, OTP codes, full customer PII, or session
# tokens — existing call sites (e.g. apps/sms) already avoid this; this
# config does not add anything that would start doing so.
#
# "payment" is a reserved logger namespace for the future Zibal integration
# (see docs/00_PROJECT_MASTER_REFERENCE.md) — payment code should log via
# logging.getLogger("payment") once written, and will inherit this config
# automatically without further changes here.
LOG_LEVEL = resolve_log_level()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            "format": "[{asctime}] {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
        "payment": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Business defaults (Stage 2 will read these in the pricing service)
SHOP_FREE_SHIPPING_THRESHOLD = 500_000
SHOP_TAX_PERCENT = 9

# هویت عمومی پلتفرم (نه یک فروشنده‌ی خاص) — مطابق اصل جنریک‌بودن سند مشخصات
SHOP_NAME = "دیجی‌مارکت"
SHOP_TAGLINE = "فروشگاه اینترنتی چندمنظوره"
SHOP_CONTACT_PHONE = "021-91008877"
SHOP_CONTACT_EMAIL = "info@digimarket.ir"
SHOP_CONTACT_ADDRESS = "تهران، خیابان ولیعصر"

# Platform admin-subdomain suffix (Phase 1B): a Store's stable merchant admin
# host is f"{store.admin_subdomain}.{RASTISI_ADMIN_DOMAIN_SUFFIX}" — see
# apps.stores.admin_resolution. Independent of any StoreDomain (public
# storefront domain), which is why changing the public domain never affects
# this. Overridable via environment for non-".ir" deployments/tests.
RASTISI_ADMIN_DOMAIN_SUFFIX = env_str("RASTISI_ADMIN_DOMAIN_SUFFIX", "rastisi.ir")

# Owner portal (ADR-97): exact Hosts that serve the public marketing site
# (at "/") and the owner account portal (at "/app/") instead of any per-Store
# routing. Comma-separated env override for real deployments; the dev default
# below always includes the local-dev host so `runserver` works out of the
# box without any .env at all.
RASTISI_PLATFORM_HOSTS = frozenset(
    h.lower() for h in env_list(
        "RASTISI_PLATFORM_HOSTS", default=("rastisi.ir", "www.rastisi.ir", "rastisi.localhost"),
    )
)
# Platform Admin (ADR-97, host approved in ADR-101: "platformadmins.rastisi.ir",
# not "platform.rastisi.ir" — direct-URL-only, never linked from anywhere
# public, deliberately a word that doesn't read as an obvious admin path):
# exact Hosts that serve the staff/superuser-only operational dashboard.
# Deliberately a disjoint set from RASTISI_PLATFORM_HOSTS — the marketing/
# portal host must never also resolve platform admin.
RASTISI_PLATFORM_ADMIN_HOSTS = frozenset(
    h.lower() for h in env_list(
        "RASTISI_PLATFORM_ADMIN_HOSTS",
        default=("platformadmins.rastisi.ir", "platformadmins.rastisi.localhost"),
    )
)
# The one canonical host used to build absolute cross-host links back to the
# owner portal (e.g. Merchant Admin's "Back to Rastisi" link, Section H) —
# a single explicit value, not "first item of RASTISI_PLATFORM_HOSTS" (a
# frozenset has no defined iteration order). Must itself be a member of
# RASTISI_PLATFORM_HOSTS in any real deployment.
RASTISI_PLATFORM_PRIMARY_HOST = env_str("RASTISI_PLATFORM_PRIMARY_HOST", "rastisi.ir")

# Trial/platform-subdomain alphabet (ADR-94) — excludes 0/o/1/l/i to avoid
# visual ambiguity in a human-typed 9-character code.
RASTISI_PLATFORM_CODE_ALPHABET = "abcdefghjkmnpqrstuvwxyz23456789"
RASTISI_PLATFORM_CODE_LENGTH = 9

# Anti-abuse cap on how many Stores a single owner account may hold via
# active OWNER memberships (ADR-98 area). Not a billing-plan entitlement —
# apps.subscriptions has no per-owner store-count concept — this is a
# platform-wide safety limit, generous by default, overridable per deployment.
RASTISI_MAX_STORES_PER_OWNER = env_int("RASTISI_MAX_STORES_PER_OWNER", default=10)

# Owner/staff mobile-OTP identity (Section 3) — platform-level SMS sending,
# deliberately independent from apps.sms's Store-scoped ShopSettings.
# sms_backend (ADR-93): OTP for platform identity happens before/without any
# Store context, so it cannot depend on a Store's own SMS provider config.
# Reuses apps.sms.services.backends' provider classes (dev console backend
# vs. real Melipayamak) — never a duplicate backend implementation.
RASTISI_OWNER_SMS_BACKEND = env_str("RASTISI_OWNER_SMS_BACKEND", "console")
RASTISI_OWNER_SMS_USERNAME = env_str("RASTISI_OWNER_SMS_USERNAME", "")
RASTISI_OWNER_SMS_PASSWORD = env_str("RASTISI_OWNER_SMS_PASSWORD", "")
RASTISI_OWNER_SMS_SENDER = env_str("RASTISI_OWNER_SMS_SENDER", "")

# Checkpoint 5A — default subscription plan for newly onboarded stores.
# ``RASTISI_DEFAULT_PLAN_CODE`` names a Plan.code whose latest published
# version a new store is put on (via subscription_service.provision_default_
# subscription). Empty (the default) means "do not auto-assign a plan" — a
# store then falls back to fail-open entitlements until a plan is chosen, so
# turning this on is an explicit deployment decision. Existing stores are never
# touched by this (they get the unlimited Legacy plan via migration/command);
# only genuinely new stores use the default plan. ``RASTISI_DEFAULT_PLAN_START_
# TRIAL`` controls whether the default subscription begins in a trial (if the
# plan version defines trial_days) or goes straight to active.
RASTISI_DEFAULT_PLAN_CODE = env_str("RASTISI_DEFAULT_PLAN_CODE", "")
RASTISI_DEFAULT_PLAN_START_TRIAL = env_str("RASTISI_DEFAULT_PLAN_START_TRIAL", "true").lower() in ("1", "true", "yes", "on")

# Checkpoint 5B — SaaS billing configuration. The active subscription payment
# provider (default "manual" — an honest test/manual provider that never fakes
# a production payment; wire a real gateway behind the same interface later).
# Secrets come only from the environment, never the database or code.
RASTISI_BILLING_PROVIDER = env_str("RASTISI_BILLING_PROVIDER", "manual")
RASTISI_BILLING_WEBHOOK_SECRET = env_str("RASTISI_BILLING_WEBHOOK_SECRET", "")
# Max webhook body accepted before rejection (bytes) and signature timestamp
# tolerance (seconds) — see ADR-76.
RASTISI_BILLING_MAX_WEBHOOK_BYTES = env_int("RASTISI_BILLING_MAX_WEBHOOK_BYTES", default=65536)
RASTISI_BILLING_WEBHOOK_TOLERANCE_SECONDS = env_int("RASTISI_BILLING_WEBHOOK_TOLERANCE_SECONDS", default=300)
# Renewal invoices are generated this many days before the current period ends
# (ADR-78). Dunning retry schedule is days-after-due, comma-separated (ADR-79).
RASTISI_BILLING_RENEWAL_LEAD_DAYS = env_int("RASTISI_BILLING_RENEWAL_LEAD_DAYS", default=3)
RASTISI_BILLING_DUNNING_SCHEDULE = env_str("RASTISI_BILLING_DUNNING_SCHEDULE", "0,3,7,14")
# Whether SaaS billing charges tax (default off — see ADR-82). When on, a flat
# platform-wide rate is applied; legal tax compliance is out of scope.
RASTISI_BILLING_TAX_RATE = env_str("RASTISI_BILLING_TAX_RATE", "0")

# Owner-portal transactional email (ADR-93) — password reset only today.
# Console backend by default (dev/test: visible in server logs, never
# silently "sent"); production sets DJANGO_EMAIL_BACKEND to the real SMTP
# backend plus the DJANGO_EMAIL_HOST* variables below. Never a fake success.
EMAIL_BACKEND = env_str("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env_str("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = env_int("DJANGO_EMAIL_PORT", default=587)
EMAIL_HOST_USER = env_str("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env_str("DJANGO_EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("DJANGO_EMAIL_USE_TLS", default=True)
DEFAULT_FROM_EMAIL = env_str("DJANGO_DEFAULT_FROM_EMAIL", "no-reply@rastisi.ir")
