# Generated by Django 5.2.16 on 2026-07-30 23:02

import apps.portal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0009_storedomain_domain_type_and_redirect"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("full_name", models.CharField(max_length=150, verbose_name="نام")),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="موضوع"
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "is_reviewed",
                    models.BooleanField(default=False, verbose_name="بررسی\u200cشده"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "پیام\u200cهای تماس",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OwnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل مالک",
                "verbose_name_plural": "پروفایل\u200cهای مالک",
            },
        ),
        migrations.CreateModel(
            name="AdminHandoffTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.portal.models._generate_handoff_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="توکن",
                    ),
                ),
                (
                    "destination_path",
                    models.CharField(
                        default="/admin-portal/",
                        max_length=200,
                        verbose_name="مسیر مقصد",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان مصرف"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_handoff_tickets",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_handoff_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلیت ورود به پنل مدیریت",
                "verbose_name_plural": "بلیت\u200cهای ورود به پنل مدیریت",
                "indexes": [
                    models.Index(
                        fields=["token", "consumed_at"],
                        name="idx_handoff_token_consumed",
                    )
                ],
            },
        ),
    ]
