# Generated by Django 5.2.16 on 2026-07-31 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "default_trial_days",
                    models.PositiveIntegerField(
                        default=30,
                        verbose_name="روزهای پیش\u200cفرض دوره\u200cی آزمایشی",
                    ),
                ),
                (
                    "deletion_retention_days",
                    models.PositiveIntegerField(
                        default=365,
                        help_text="بین ۱۸۰ تا ۳۶۵ روز (۶ تا ۱۲ ماه).",
                        verbose_name="روزهای نگهداریِ داده پس از درخواست حذف",
                    ),
                ),
                (
                    "primary_brand_color",
                    models.CharField(
                        default="#10a37a", max_length=7, verbose_name="رنگ اصلی برند"
                    ),
                ),
                (
                    "secondary_brand_color",
                    models.CharField(
                        default="#e0a72e", max_length=7, verbose_name="رنگ ثانویه برند"
                    ),
                ),
                (
                    "temporary_logo_text",
                    models.CharField(
                        default="راستیسی",
                        help_text="تا زمانی\u200cکه لوگوی نهایی آپلود نشده، همین\u200cجا نمایش داده می\u200cشود.",
                        max_length=20,
                        verbose_name="نشان موقت برند (متنی)",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="platform/",
                        verbose_name="لوگوی نهایی",
                    ),
                ),
                (
                    "support_contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="تلفن پشتیبانی",
                    ),
                ),
                (
                    "support_contact_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="ایمیل پشتیبانی",
                    ),
                ),
                (
                    "step_up_actions",
                    models.JSONField(
                        default=dict,
                        help_text="نگاشتِ کلیدِ عملیات به روشن/خاموش — فقط کلیدهای STEP_UP_ACTION_CHOICES مجازند.",
                        verbose_name="سیاست تأیید مجدد (Step-up OTP)",
                    ),
                ),
                (
                    "default_payment_provider",
                    models.CharField(
                        default="manual",
                        max_length=40,
                        verbose_name="درگاه پرداخت پیش\u200cفرض",
                    ),
                ),
                (
                    "enabled_payment_providers",
                    models.JSONField(
                        default=list,
                        help_text="فهرستِ کدهای درگاه فعال — نمایش\u200cدادنی در تسویه\u200cحساب اشتراک.",
                        verbose_name="درگاه\u200cهای پرداخت فعال",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پلتفرم",
                "verbose_name_plural": "تنظیمات پلتفرم",
            },
        ),
        migrations.CreateModel(
            name="PlatformAuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "action_code",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="کد عملیات"
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, default="", max_length=60, verbose_name="نوع شیء"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="شناسه\u200cی شیء",
                    ),
                ),
                (
                    "object_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="برچسبِ شیء",
                    ),
                ),
                (
                    "before_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="خلاصه\u200cی پیش از تغییر"
                    ),
                ),
                (
                    "after_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="خلاصه\u200cی پس از تغییر"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="متادیتا"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("success", "موفق"), ("failure", "ناموفق")],
                        default="success",
                        max_length=10,
                        verbose_name="نتیجه",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_audit_log_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "رخداد حسابرسی پلتفرم",
                "verbose_name_plural": "رخدادهای حسابرسی پلتفرم",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_code", "created_at"],
                        name="idx_pf_audit_action_created",
                    )
                ],
            },
        ),
    ]
