# Generated by Django 5.2.16 on 2026-07-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_platform_configuration_and_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="فرمتِ متعارف ۰۹xxxxxxxxx — شناسه\u200cی اصلیِ ورودِ OTP (Section 3).",
                max_length=15,
                null=True,
                unique=True,
                verbose_name="موبایل",
            ),
        ),
        migrations.CreateModel(
            name="OwnerOtpChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="موبایل"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[("register", "ثبت\u200cنام"), ("login", "ورود")],
                        max_length=10,
                        verbose_name="هدف",
                    ),
                ),
                ("code_hash", models.CharField(max_length=200, verbose_name="هَشِ کد")),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="تعداد تلاشِ تأیید"
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان مصرف"
                    ),
                ),
            ],
            options={
                "verbose_name": "کدِ یکبارمصرفِ مالک",
                "verbose_name_plural": "کدهای یکبارمصرفِ مالک",
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "created_at"],
                        name="idx_owner_otp_phone_purpose",
                    )
                ],
            },
        ),
    ]
