# Generated by Django 5.2.16 on 2026-07-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_owner_otp_and_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerotpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "ثبت\u200cنام"),
                    ("login", "ورود"),
                    ("step_up", "تأییدِ عملیاتِ حساس (Section 10)"),
                ],
                max_length=10,
                verbose_name="هدف",
            ),
        ),
    ]
