# Generated by Django 5.2.16 on 2026-08-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_alter_ownerotpchallenge_purpose"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfiguration",
            name="encrypted_sms_credentials",
            field=models.TextField(
                blank=True,
                default="",
                help_text="مقدارِ رمزنگاری\u200cشده — هرگز مستقیم خوانده نمی\u200cشود",
                verbose_name="اعتبارنامه\u200cی پیامکِ رمزنگاری\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="sms_backend",
            field=models.CharField(
                blank=True,
                choices=[
                    ("console", "کنسول (فقط لاگ، برای توسعه)"),
                    ("melipayamak", "ملی\u200cپیامک"),
                    ("kavenegar", "کاوه\u200cنگار"),
                ],
                default="console",
                max_length=20,
                verbose_name="درگاهِ پیامکِ مرکزی",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="sms_sender_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="شماره\u200cی فرستنده\u200cی مرکزی",
            ),
        ),
    ]
