# Generated by Django 5.2.16 on 2026-08-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_platformconfiguration_sms_fields"),
        ("stores", "0017_platform_owner_admin_gap_fill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminhandoffticket",
            name="issued_by_platform_admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_support_handoff_tickets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="صادرشده توسطِ مدیرِ پلتفرم (پشتیبانی)",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="maintenance_mode_enabled",
            field=models.BooleanField(
                default=False,
                help_text="روشن یعنی پرتالِ مالک/فروشگاه\u200cسازیِ تازه موقتاً در دسترسِ عمومی نیست.",
                verbose_name="حالتِ تعمیرات",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="new_store_registration_enabled",
            field=models.BooleanField(
                default=True, verbose_name="ثبت\u200cنامِ فروشگاهِ تازه فعال است"
            ),
        ),
        migrations.CreateModel(
            name="PlatformInternalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("body", models.TextField(verbose_name="متنِ یادداشت")),
                (
                    "about_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_internal_notes_about",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="درباره\u200cی کاربر",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authored_platform_internal_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_internal_notes",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشتِ داخلیِ پلتفرم",
                "verbose_name_plural": "یادداشت\u200cهایِ داخلیِ پلتفرم",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("store__isnull", False), ("about_user__isnull", True)
                            ),
                            models.Q(
                                ("store__isnull", True), ("about_user__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="platforminternalnote_exactly_one_subject",
                    )
                ],
            },
        ),
    ]
