# Generated by Django 5.2.17 on 2026-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0007_platformconfiguration_enamad_verification_meta_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfiguration",
            name="encrypted_zibal_credentials",
            field=models.TextField(
                blank=True,
                default="",
                help_text="مقدارِ رمزنگاری\u200cشده — هرگز مستقیم خوانده نمی\u200cشود",
                verbose_name="اعتبارنامه\u200cی زیبالِ پلتفرمِ رمزنگاری\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="zibal_sandbox_mode",
            field=models.BooleanField(
                default=False,
                help_text="در حالتِ آزمایشی، merchant واقعی نادیده گرفته و مقدارِ Sandbox زیبال استفاده می\u200cشود.",
                verbose_name="حالتِ آزمایشیِ زیبال (Sandbox)",
            ),
        ),
        migrations.AlterField(
            model_name="platformconfiguration",
            name="default_payment_provider",
            field=models.CharField(
                choices=[("manual", "دستی (بدونِ درگاهِ واقعی)"), ("zibal", "زیبال")],
                default="manual",
                help_text="Providerِ فعالِ پرداختِ اشتراکِ خودِ پلتفرم — جدا از درگاهِ پرداختِ سفارشِ هر Store.",
                max_length=40,
                verbose_name="درگاه پرداخت پیش\u200cفرض",
            ),
        ),
    ]
