# Generated by Django 5.2.17 on 2026-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0008_platformconfiguration_encrypted_zibal_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformconfiguration",
            name="enamad_auth_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                verbose_name="کدِ تأییدِ نمادِ نهاییِ پلتفرم",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="enamad_badge_enabled",
            field=models.BooleanField(
                default=False,
                help_text="حتی اگر شناسه/کد ثبت شده باشد، تا این کلید روشن نشود نماد نمایش داده نمی\u200cشود.",
                verbose_name="نمایشِ نمادِ نهایی فعال است",
            ),
        ),
        migrations.AddField(
            model_name="platformconfiguration",
            name="enamad_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                verbose_name="شناسه\u200cی نمادِ نهاییِ پلتفرم",
            ),
        ),
    ]
