# Generated by Django 5.2.17 on 2026-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0009_platformconfiguration_enamad_auth_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerotpchallenge",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("register", "ثبت\u200cنام"),
                    ("login", "ورود"),
                    ("step_up", "تأییدِ عملیاتِ حساس (Section 10)"),
                    ("reset", "بازیابیِ رمزِ عبور با موبایل"),
                ],
                max_length=10,
                verbose_name="هدف",
            ),
        ),
    ]
