# Generated by Django 5.2.16 on 2026-07-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="موبایل"
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="کد")),
                ("expires_at", models.DateTimeField(verbose_name="زمان انقضا")),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد تلاش تأیید"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="مصرف\u200cشده"),
                ),
            ],
            options={
                "verbose_name": "کد یکبار مصرف",
                "verbose_name_plural": "کدهای یکبار مصرف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "event_key",
                    models.CharField(
                        choices=[
                            ("welcome", "ثبت\u200cنام / خوش\u200cآمدگویی"),
                            ("otp", "کد ورود یکبار مصرف"),
                            ("order_placed", "ثبت سفارش"),
                            ("payment_success", "پرداخت موفق"),
                            ("payment_failed", "پرداخت ناموفق"),
                            ("order_processing", "سفارش در حال پردازش"),
                            ("order_shipped", "ارسال سفارش"),
                            ("order_delivered", "تحویل سفارش"),
                            ("order_canceled", "لغو سفارش"),
                        ],
                        max_length=30,
                        verbose_name="رویداد",
                    ),
                ),
                ("recipient", models.CharField(max_length=15, verbose_name="گیرنده")),
                ("message", models.TextField(verbose_name="متن نهایی")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("sent", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیام خطا"),
                ),
                (
                    "provider_ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="شناسه\u200cی ارجاع سرویس",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد تلاش"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش پیامک",
                "verbose_name_plural": "گزارش پیامک\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "event_key",
                    models.CharField(
                        choices=[
                            ("welcome", "ثبت\u200cنام / خوش\u200cآمدگویی"),
                            ("otp", "کد ورود یکبار مصرف"),
                            ("order_placed", "ثبت سفارش"),
                            ("payment_success", "پرداخت موفق"),
                            ("payment_failed", "پرداخت ناموفق"),
                            ("order_processing", "سفارش در حال پردازش"),
                            ("order_shipped", "ارسال سفارش"),
                            ("order_delivered", "تحویل سفارش"),
                            ("order_canceled", "لغو سفارش"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="رویداد",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                ("body", models.TextField(verbose_name="متن قالب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "قالب پیامک",
                "verbose_name_plural": "قالب\u200cهای پیامک",
                "ordering": ["event_key"],
            },
        ),
    ]
