# Generated by Django 5.2.16 on 2026-07-31 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0002_otpcode_code_hash"),
        ("stores", "0015_storeownershiptransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsOutboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="گیرنده")),
                ("message", models.TextField(verbose_name="متن پیامک")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("sending", "در حالِ ارسال"),
                            ("sent", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "provider_ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="شناسه\u200cی ارجاعِ گیت\u200cوی",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیامِ خطا"),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعدادِ claim"),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ claim"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ ارسال"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_outbox_items",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیامِ صفِ SmsRasti",
                "verbose_name_plural": "پیام\u200cهایِ صفِ SmsRasti",
                "ordering": ["created_at"],
            },
        ),
    ]
