# Generated by Django 5.2.16 on 2026-07-31 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_smsoutboxitem"),
        ("stores", "0015_storeownershiptransfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="smslog",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sms_logs",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
    ]
