# Generated by Django 5.2.16 on 2026-08-01 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_smslog_store"),
        ("stores", "0015_storeownershiptransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام بسته")),
                (
                    "credit_amount",
                    models.PositiveIntegerField(verbose_name="تعدادِ اعتبار"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="قیمت (تومان)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیبِ نمایش"),
                ),
            ],
            options={
                "verbose_name": "بسته\u200cی پیامک",
                "verbose_name_plural": "بسته\u200cهای پیامک",
                "ordering": ["display_order", "credit_amount"],
            },
        ),
        migrations.CreateModel(
            name="SmsBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "credits",
                    models.IntegerField(
                        default=0, verbose_name="اعتبارِ باقی\u200cمانده"
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_balance",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعتبارِ پیامکِ فروشگاه",
                "verbose_name_plural": "اعتبارهایِ پیامکِ فروشگاه",
            },
        ),
        migrations.CreateModel(
            name="SmsPackagePurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "credit_amount",
                    models.PositiveIntegerField(
                        verbose_name="تعدادِ اعتبار (اسنپ\u200cشات)"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=12,
                        verbose_name="قیمت (اسنپ\u200cشات، تومان)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظارِ تکمیل"),
                            ("completed", "تکمیل\u200cشده"),
                            ("canceled", "لغوشده"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ تکمیل"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="sms.smspackage",
                        verbose_name="بسته",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_package_purchases",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "خریدِ بسته\u200cی پیامک",
                "verbose_name_plural": "خریدهایِ بسته\u200cی پیامک",
                "ordering": ["-created_at"],
            },
        ),
    ]
