# Generated by Django 5.2.16 on 2026-08-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_seed_sms_packages"),
        ("stores", "0017_platform_owner_admin_gap_fill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsCreditAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("delta", models.IntegerField(verbose_name="مقدارِ تغییر")),
                (
                    "balance_before",
                    models.IntegerField(verbose_name="اعتبارِ پیش از تغییر"),
                ),
                (
                    "balance_after",
                    models.IntegerField(verbose_name="اعتبارِ پس از تغییر"),
                ),
                ("reason", models.CharField(max_length=200, verbose_name="دلیل")),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="یادداشتِ داخلی",
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_credit_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_credit_adjustments",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اصلاحِ اعتبارِ پیامک",
                "verbose_name_plural": "اصلاح\u200cهایِ اعتبارِ پیامک",
                "ordering": ["-created_at"],
            },
        ),
    ]
