# Generated by Django 5.2.16 on 2026-07-25 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="شناسه\u200cی عمومی پایدار برای ارجاع خارجی (API، صورتحساب، پشتیبانی).",
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام فروشگاه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="یکتای سراسری در کل پلتفرم — نه فقط در یک فروشگاه.",
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("provisioning", "در حال آماده\u200cسازی"),
                            ("active", "فعال"),
                            ("suspended", "معلق"),
                            ("closed", "بسته\u200cشده"),
                        ],
                        db_index=True,
                        default="provisioning",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
            ],
            options={
                "verbose_name": "فروشگاه",
                "verbose_name_plural": "فروشگاه\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoreDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hostname",
                    models.CharField(
                        help_text="نام میزبان نرمال\u200cشده (بدون پروتکل/مسیر/پورت).",
                        max_length=253,
                        unique=True,
                        verbose_name="نام میزبان",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, verbose_name="دامنه\u200cی اصلی"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "تأییدنشده"),
                            ("pending", "در انتظار تأیید"),
                            ("verified", "تأییدشده"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=20,
                        verbose_name="وضعیت تأیید",
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="توکن تأیید"
                    ),
                ),
                (
                    "verification_requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان درخواست تأیید"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "دامنه\u200cی فروشگاه",
                "verbose_name_plural": "دامنه\u200cهای فروشگاه",
                "ordering": ["store", "-is_primary", "hostname"],
                "indexes": [
                    models.Index(
                        fields=["store", "is_primary"], name="idx_domain_store_primary"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_primary", True)),
                        fields=("store",),
                        name="uniq_primary_domain_per_store",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("verification_token", ""), _negated=True),
                        fields=("verification_token",),
                        name="uniq_verification_token_when_set",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoreMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "مالک"),
                            ("administrator", "مدیر"),
                            ("catalog_manager", "مدیر کاتالوگ"),
                            ("order_manager", "مدیر سفارش\u200cها"),
                            ("content_editor", "ویرایشگر محتوا"),
                            ("analyst", "تحلیلگر"),
                        ],
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "دعوت\u200cشده"),
                            ("active", "فعال"),
                            ("revoked", "لغوشده"),
                        ],
                        db_index=True,
                        default="invited",
                        max_length=10,
                        verbose_name="وضعیت عضویت",
                    ),
                ),
                (
                    "invited_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان دعوت"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پذیرش"
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان لغو"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="store_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دعوت\u200cکننده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "عضویت در فروشگاه",
                "verbose_name_plural": "عضویت\u200cهای فروشگاه",
                "ordering": ["store", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "user"), name="uniq_membership_per_store_user"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("role", "owner"), ("status", "active")),
                        fields=("store",),
                        name="uniq_active_owner_per_store",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "active"), _negated=True),
                            ("accepted_at__isnull", False),
                            _connector="OR",
                        ),
                        name="active_membership_requires_accepted_at",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "revoked"), _negated=True),
                            ("revoked_at__isnull", False),
                            _connector="OR",
                        ),
                        name="revoked_membership_requires_revoked_at",
                    ),
                ],
            },
        ),
    ]
