# Generated by Django 5.2.16 on 2026-07-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0009_storedomain_domain_type_and_redirect"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="storedomain",
            name="redirect_alias_domain_is_never_primary",
        ),
        migrations.RemoveField(
            model_name="storedomain",
            name="is_redirect",
        ),
        migrations.AddField(
            model_name="storedomain",
            name="retired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="وقتی مقداردهی شده، این نام میزبان دیگر هرگز چیزی نمایش نمی\u200cدهد — نه محتوای فروشگاه، نه تغییرمسیر (ADR-101؛ جایگزینِ رفتارِ تغییرمسیرِ همیشگیِ ADR-96 که کنار گذاشته شد). درخواست به این نام میزبان یک پاسخِ امنِ «غیرفعال/یافت\u200cنشد» می\u200cگیرد (domain_is_eligible_for_routing این ردیف را واجد شرایط نمی\u200cداند). ردیف هرگز حذف نمی\u200cشود و hostname برای همیشه یکتا می\u200cماند — پس این نام میزبان هرگز به فروشگاه دیگری واگذار نمی\u200cشود، فقط دیگر به هیچ\u200cجا نمی\u200cرود.",
                null=True,
                verbose_name="زمان بازنشستگی",
            ),
        ),
        migrations.AddConstraint(
            model_name="storedomain",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retired_at__isnull", True), ("is_primary", False), _connector="OR"
                ),
                name="retired_domain_is_never_primary",
            ),
        ),
    ]
