# Generated by Django 5.2.16 on 2026-07-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0010_storedomain_retire_instead_of_redirect"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="تا این مقدار خالی است، فروشگاه خصوصی است (Section 6) — فقط برایِ مالک/کارکنانِ عضو با پیش\u200cنمایشِ احرازهویت\u200cشده قابل\u200cدیدن، نه برایِ بازدیدکنندهٔ ناشناس، حتی اگر Store.status=active باشد. ``apps.stores.services.publication_service`` تنها جایِ مجاز برایِ خواندنِ این مقدار در تصمیمِ «آیا این فروشگاه اکنون عمومی/در دسترس است؟» است.",
                null=True,
                verbose_name="زمان تکمیل راه\u200cاندازی",
            ),
        ),
    ]
