# Generated by Django 5.2.16 on 2026-07-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0012_backfill_store_onboarding_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="onboarding_stage",
            field=models.CharField(
                choices=[
                    ("identity", "معرفیِ فروشگاه"),
                    ("industry", "انتخابِ صنف"),
                    ("branding", "هویتِ بصری"),
                    ("review", "بازبینی و انتشار"),
                    ("done", "تکمیل\u200cشده"),
                ],
                default="identity",
                help_text="پیشرفتِ ویزاردِ آنبوردینگ (Section 5) — صرفاً برای هدایتِ مالک به همان\u200cجایی که رها کرده (save-progress)، نه یک قفلِ سخت\u200cگیرانه: مالک همیشه می\u200cتواند آزادانه به مراحلِ قبلی برگردد و آن\u200cها را دوباره ویرایش کند. تنها گذرِ صریح از مرحله\u200cی REVIEW است که ``onboarding_completed_at`` را مقداردهی می\u200cکند.",
                max_length=20,
                verbose_name="مرحله\u200cی جاریِ راه\u200cاندازی",
            ),
        ),
    ]
