# Generated by Django 5.2.16 on 2026-07-31 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0013_store_onboarding_stage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="deletion_requested_at",
            field=models.DateTimeField(
                blank=True,
                help_text="حذف همیشه نرم است (Section 14) — تا این\u200cجا مقداردهی شده، ``status=CLOSED`` و فروشگاه غیرِ عمومی است، اما هیچ داده\u200cای پاک نمی\u200cشود؛ فقط پس از رسیدنِ به ``deletion_scheduled_purge_at``، دستورِ ``purge_deleted_stores`` می\u200cتواند واقعاً حذف کند.",
                null=True,
                verbose_name="زمانِ درخواستِ حذف",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="deletion_requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_store_deletions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="درخواست\u200cدهنده\u200cی حذف",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="deletion_scheduled_purge_at",
            field=models.DateTimeField(
                blank=True,
                help_text="از زمانِ درخواست به\u200cاضافه\u200cی PlatformConfiguration.deletion_retention_days محاسبه می\u200cشود.",
                null=True,
                verbose_name="زمانِ برنامه\u200cریزی\u200cشده\u200cی پاک\u200cسازیِ نهایی",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="pre_deletion_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("provisioning", "در حال آماده\u200cسازی"),
                    ("active", "فعال"),
                    ("suspended", "معلق"),
                    ("closed", "بسته\u200cشده"),
                ],
                default="",
                help_text="برایِ بازگردانیِ دقیق در صورتِ لغوِ درخواستِ حذف (cancel_deletion).",
                max_length=20,
                verbose_name="وضعیتِ پیش از درخواستِ حذف",
            ),
        ),
    ]
