# Generated by Django 5.2.16 on 2026-07-31 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0014_store_deletion_requested_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreOwnershipTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_phone",
                    models.CharField(max_length=15, verbose_name="موبایلِ مالکِ جدید"),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False,
                        max_length=32,
                        unique=True,
                        verbose_name="توکنِ پذیرش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظارِ پذیرش"),
                            ("completed", "انجام\u200cشده"),
                            ("expired", "منقضی\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="زمانِ انقضا")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ تکمیل"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ لغو"
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ownership_transfers_initiated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آغازکننده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_transfers",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "انتقالِ مالکیتِ فروشگاه",
                "verbose_name_plural": "انتقال\u200cهایِ مالکیتِ فروشگاه",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("store",),
                        name="uniq_pending_ownership_transfer_per_store",
                    )
                ],
            },
        ),
    ]
