# Generated by Django 5.2.16 on 2026-08-01 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0015_storeownershiptransfer"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreIntegrationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_code",
                    models.CharField(max_length=40, verbose_name="کدِ Provider"),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "encrypted_credentials",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="مقدارِ رمزنگاری\u200cشده — هرگز مستقیم خوانده نمی\u200cشود",
                        verbose_name="اعتبارنامه\u200cی رمزنگاری\u200cشده",
                    ),
                ),
                (
                    "last_tested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین تستِ اتصال"
                    ),
                ),
                (
                    "last_test_result",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="نتیجه\u200cی آخرین تست",
                    ),
                ),
                (
                    "last_test_message",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="پیامِ آخرین تست",
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ اتصال"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_connections",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اتصالِ یکپارچه\u200cسازیِ فروشگاه",
                "verbose_name_plural": "اتصال\u200cهایِ یکپارچه\u200cسازیِ فروشگاه",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("store", "provider_code"),
                        name="uniq_integration_per_store_provider",
                    )
                ],
            },
        ),
    ]
