# Generated by Django 5.2.16 on 2026-08-03 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0016_store_integration_connection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="suspended_at",
            field=models.DateTimeField(
                blank=True,
                help_text="مقداردهی\u200cشده یعنی این Store توسطِ مدیرِ پلتفرم تعلیق شده — نگاه کنید به apps.stores.services.store_status_service. جدا از ``status=SUSPENDED`` نگه\u200cداشته می\u200cشود تا زمان/دلیل/فاعلِ تعلیق حتی پس از فعال\u200cسازیِ دوباره هم در تاریخچه قابل\u200cبازیابی بماند.",
                null=True,
                verbose_name="زمانِ تعلیق",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="suspended_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suspended_stores",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تعلیق\u200cکننده",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="suspension_reason",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="دلیلِ تعلیق"
            ),
        ),
    ]
