# Generated by Django 5.2.16 on 2026-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_cover",
            field=models.BooleanField(default=False, verbose_name="تصویر اصلی (کاور)"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/thumbnails/",
                verbose_name="تصویر بندانگشتی",
            ),
        ),
    ]
