# Generated by Django 5.2.16 on 2026-07-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productimage_is_cover_productimage_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="عنوان مشخصه")),
                (
                    "value",
                    models.CharField(blank=True, max_length=300, verbose_name="مقدار"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "مشخصه فنی",
                "verbose_name_plural": "مشخصات فنی",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SpecificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام قالب"
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب مشخصات",
                "verbose_name_plural": "قالب\u200cهای مشخصات",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpecificationTemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=100, verbose_name="عنوان مشخصه")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
            ],
            options={
                "verbose_name": "فیلد قالب مشخصات",
                "verbose_name_plural": "فیلدهای قالب مشخصات",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={
                "ordering": ["display_order", "attribute", "value"],
                "verbose_name": "تنوع کالا",
                "verbose_name_plural": "تنوع\u200cهای کالا",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("simple", "کالای ساده"), ("variable", "کالای دارای تنوع")],
                default="simple",
                max_length=10,
                verbose_name="نوع کالا",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="normalized_attribute",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="normalized_value",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=80
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sku",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="کد کالا (SKU)"
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="attribute",
            field=models.CharField(max_length=60, verbose_name="نام تنوع"),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="extra_price",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="تغییر قیمت (تومان)",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="value",
            field=models.CharField(max_length=60, verbose_name="مقدار تنوع"),
        ),
        migrations.AddField(
            model_name="specification",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="catalog.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AddField(
            model_name="specificationtemplate",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="specification_templates",
                to="catalog.category",
                verbose_name="دسته\u200cبندی مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="specificationtemplatefield",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="catalog.specificationtemplate",
                verbose_name="قالب",
            ),
        ),
        migrations.AddConstraint(
            model_name="specificationtemplatefield",
            constraint=models.UniqueConstraint(
                fields=("template", "label"), name="uniq_template_field_label"
            ),
        ),
    ]
