# Generated by Django 5.2.16 on 2026-07-25 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_variant_backfill_and_constraints"),
        ("stores", "0002_create_akhlaghi_store"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="uniq_variant_sku_when_set",
        ),
        migrations.AddField(
            model_name="brand",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_variants",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="store",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendors",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=140, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=140, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=40, verbose_name="کد کالا (SKU)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=240, verbose_name="اسلاگ"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=170, verbose_name="اسلاگ"
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="uniq_brand_slug_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="uniq_category_slug_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="uniq_product_slug_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("store", "sku"), name="uniq_product_sku_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sku", ""), _negated=True),
                fields=("store", "sku"),
                name="uniq_variant_sku_when_set",
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="uniq_vendor_slug_per_store"
            ),
        ),
    ]
