# Generated by Django 5.2.16 on 2026-07-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_store_scope_catalog_enforce_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="بارکد محصول"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="requires_shipping",
            field=models.BooleanField(
                default=True, verbose_name="نیاز به ارسال فیزیکی"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_description",
            field=models.CharField(
                blank=True, default="", max_length=160, verbose_name="توضیحات متا"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="seo_title",
            field=models.CharField(
                blank=True, default="", max_length=70, verbose_name="عنوان سئو"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="وزن (گرم)"
            ),
        ),
    ]
