# Generated by Django 5.2.16 on 2026-07-28 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_logistics_and_seo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="catalog.productvariant",
                verbose_name="تنوع مرتبط",
            ),
        ),
    ]
