# Generated by Django 5.2.16 on 2026-07-29 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_image_variant"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد داخلی"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=120, verbose_name="عنوان نمایشی"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "متن"),
                            ("number", "عدد"),
                            ("boolean", "بله/خیر"),
                            ("select", "تک\u200cانتخابی"),
                            ("multiselect", "چندانتخابی"),
                            ("color", "رنگ"),
                            ("date", "تاریخ"),
                        ],
                        default="text",
                        max_length=12,
                        verbose_name="نوع داده",
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "متن ساده"),
                            ("dropdown", "کشویی"),
                            ("swatch", "نمونه (رنگ/تصویر)"),
                            ("checkbox", "چک\u200cباکس"),
                            ("radio", "دکمه رادیویی"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="نوع نمایش",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=30, verbose_name="واحد"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="الزامی"),
                ),
                (
                    "is_filterable",
                    models.BooleanField(default=False, verbose_name="قابل فیلتر"),
                ),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=False, verbose_name="قابل جست\u200cوجو"
                    ),
                ),
                (
                    "is_comparable",
                    models.BooleanField(default=False, verbose_name="قابل مقایسه"),
                ),
                (
                    "is_variant_axis",
                    models.BooleanField(
                        default=False, verbose_name="واجد شرایط محور تنوع"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "ویژگی",
                "verbose_name_plural": "ویژگی\u200cها",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="برچسب")),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="مقدار داخلی",
                    ),
                ),
                (
                    "normalized_label",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=140
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="کد رنگ (Hex)"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "مقدار ویژگی",
                "verbose_name_plural": "مقادیر ویژگی",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "text_value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="مقدار متنی",
                    ),
                ),
                (
                    "number_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="مقدار عددی",
                    ),
                ),
                (
                    "boolean_value",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="مقدار بولی"
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی کالا",
                "verbose_name_plural": "مقادیر ویژگی کالا",
                "ordering": ["attribute__display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=60, verbose_name="عنوان محور")),
                (
                    "normalized_label",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=80
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="موقعیت"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "محور تنوع کالا",
                "verbose_name_plural": "محورهای تنوع کالا",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=60, verbose_name="برچسب")),
                (
                    "normalized_label",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=80
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="کد رنگ (Hex)"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "مقدار محور تنوع",
                "verbose_name_plural": "مقادیر محور تنوع",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="VariantOptionValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مقدار محورِ تنوع",
                "verbose_name_plural": "مقادیر محورهای تنوع",
            },
        ),
        migrations.AddField(
            model_name="productvariant",
            name="barcode",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="بارکد"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="combination_key",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=64
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="قیمت مقایسه\u200cای (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="بهای تمام\u200cشده (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="height_mm",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="ارتفاع (میلی\u200cمتر)"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="تنوع پیش\u200cفرض"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="is_obsolete",
            field=models.BooleanField(
                default=False,
                verbose_name="منسوخ (دیگر با محورهای فعال کالا مطابقت ندارد)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="length_mm",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="طول (میلی\u200cمتر)"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="آستانه\u200cی هشدار کمبود موجودی"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="track_inventory",
            field=models.BooleanField(default=True, verbose_name="پیگیری موجودی"),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="weight_grams",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="وزن (گرم)"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="width_mm",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="عرض (میلی\u200cمتر)"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("combination_key", ""), _negated=True),
                fields=("product", "combination_key"),
                name="uniq_variant_combination_key_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("product",),
                name="uniq_default_variant_per_product",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="catalog.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="stores.store",
                verbose_name="فروشگاه",
            ),
        ),
        migrations.AddField(
            model_name="attributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="catalog.attribute",
                verbose_name="ویژگی",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_assignments",
                to="catalog.attribute",
                verbose_name="ویژگی",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attribute_values",
                to="catalog.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AddField(
            model_name="productattributevalue",
            name="value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_assignments",
                to="catalog.attributevalue",
                verbose_name="مقدار",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_options",
                to="catalog.attribute",
                verbose_name="ویژگی مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="catalog.product",
                verbose_name="کالا",
            ),
        ),
        migrations.AddField(
            model_name="productoptionvalue",
            name="attribute_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="option_values",
                to="catalog.attributevalue",
                verbose_name="مقدار ویژگی مرتبط",
            ),
        ),
        migrations.AddField(
            model_name="productoptionvalue",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="catalog.productoption",
                verbose_name="محور",
            ),
        ),
        migrations.AddField(
            model_name="variantoptionvalue",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_links",
                to="catalog.productoption",
                verbose_name="محور",
            ),
        ),
        migrations.AddField(
            model_name="variantoptionvalue",
            name="option_value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variant_links",
                to="catalog.productoptionvalue",
                verbose_name="مقدار",
            ),
        ),
        migrations.AddField(
            model_name="variantoptionvalue",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_values",
                to="catalog.productvariant",
                verbose_name="تنوع",
            ),
        ),
        migrations.AddConstraint(
            model_name="attribute",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_attribute_code_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("attribute", "normalized_label"),
                name="uniq_active_attribute_value_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.UniqueConstraint(
                fields=("product", "attribute", "value"),
                name="uniq_product_attribute_value",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                fields=("product", "position"), name="uniq_option_position_per_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="productoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("product", "normalized_label"),
                name="uniq_active_option_label_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="productoptionvalue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("option", "normalized_label"),
                name="uniq_active_option_value_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="variantoptionvalue",
            constraint=models.UniqueConstraint(
                fields=("variant", "option"), name="uniq_variant_option_axis"
            ),
        ),
        migrations.AddConstraint(
            model_name="variantoptionvalue",
            constraint=models.UniqueConstraint(
                fields=("variant", "option_value"), name="uniq_variant_option_value"
            ),
        ),
    ]
