# Generated by Django 5.2.16 on 2026-07-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_attribute_option_variant_engine"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("slug", models.SlugField(max_length=60, verbose_name="اسلاگ")),
                ("name", models.CharField(max_length=120, verbose_name="نام صنف")),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=20, verbose_name="آیکون"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="نسخه"),
                ),
                (
                    "locale",
                    models.CharField(default="fa", max_length=10, verbose_name="زبان"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "قالب صنف",
                "verbose_name_plural": "قالب\u200cهای صنف",
                "ordering": ["display_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "version"),
                        name="uniq_industry_template_slug_version",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="IndustryTemplateAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد پایدار"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=120, verbose_name="عنوان نمایشی"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "متن"),
                            ("number", "عدد"),
                            ("boolean", "بله/خیر"),
                            ("select", "تک\u200cانتخابی"),
                            ("multiselect", "چندانتخابی"),
                            ("color", "رنگ"),
                            ("date", "تاریخ"),
                        ],
                        default="text",
                        max_length=12,
                        verbose_name="نوع داده",
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "متن ساده"),
                            ("dropdown", "کشویی"),
                            ("swatch", "نمونه (رنگ/تصویر)"),
                            ("checkbox", "چک\u200cباکس"),
                            ("radio", "دکمه رادیویی"),
                        ],
                        default="",
                        max_length=12,
                        verbose_name="نوع نمایش",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=30, verbose_name="واحد"),
                ),
                (
                    "is_variant_axis",
                    models.BooleanField(
                        default=False, verbose_name="واجد شرایط محور تنوع"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "industry_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="catalog.industrytemplate",
                        verbose_name="قالب صنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویژگی قالب صنف",
                "verbose_name_plural": "ویژگی\u200cهای قالب صنف",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="source_template_attribute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installed_attributes",
                to="catalog.industrytemplateattribute",
                verbose_name="ویژگی مبدأ در قالب صنف",
            ),
        ),
        migrations.CreateModel(
            name="IndustryTemplateAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="برچسب")),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="مقدار داخلی",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="کد رنگ (Hex)"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "template_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.industrytemplateattribute",
                        verbose_name="ویژگی قالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "مقدار ویژگی قالب صنف",
                "verbose_name_plural": "مقادیر ویژگی قالب صنف",
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="IndustryTemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد پایدار"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="نام")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=20, verbose_name="آیکون"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "industry_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="catalog.industrytemplate",
                        verbose_name="قالب صنف",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.industrytemplatecategory",
                        verbose_name="دسته\u200cی والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی قالب صنف",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای قالب صنف",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="category",
            name="source_template_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installed_categories",
                to="catalog.industrytemplatecategory",
                verbose_name="دسته\u200cی مبدأ در قالب صنف",
            ),
        ),
        migrations.CreateModel(
            name="IndustryTemplateCategoryAttributeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="گروه/بخش"
                    ),
                ),
                (
                    "group_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب گروه"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="الزامی"),
                ),
                (
                    "is_filterable",
                    models.BooleanField(default=False, verbose_name="قابل فیلتر"),
                ),
                (
                    "is_comparable",
                    models.BooleanField(default=False, verbose_name="قابل مقایسه"),
                ),
                (
                    "is_searchable",
                    models.BooleanField(
                        default=False, verbose_name="قابل جست\u200cوجو"
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="متن راهنما",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="متن جای\u200cگیر",
                    ),
                ),
                (
                    "template_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_mappings",
                        to="catalog.industrytemplateattribute",
                        verbose_name="ویژگی قالب",
                    ),
                ),
                (
                    "template_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_mappings",
                        to="catalog.industrytemplatecategory",
                        verbose_name="دسته\u200cبندی قالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "نگاشت ویژگی-دسته\u200cبندی قالب صنف",
                "verbose_name_plural": "نگاشت\u200cهای ویژگی-دسته\u200cبندی قالب صنف",
                "ordering": ["group_order", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="CategoryAttributeSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="گروه/بخش"
                    ),
                ),
                (
                    "group_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب گروه"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="الزامی"),
                ),
                (
                    "is_filterable_override",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="قابل فیلتر (بازنویسی)"
                    ),
                ),
                (
                    "is_comparable_override",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="قابل مقایسه (بازنویسی)"
                    ),
                ),
                (
                    "is_searchable_override",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="قابل جست\u200cوجو (بازنویسی)",
                    ),
                ),
                (
                    "help_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=300,
                        verbose_name="متن راهنما",
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="متن جای\u200cگیر",
                    ),
                ),
                (
                    "is_visible_on_storefront",
                    models.BooleanField(default=True, verbose_name="نمایش در فروشگاه"),
                ),
                (
                    "is_inherited_by_children",
                    models.BooleanField(
                        default=True, verbose_name="به ارث رسیدن به زیردسته\u200cها"
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_schema_entries",
                        to="catalog.attribute",
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attribute_schema_entries",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "source_template_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_mappings",
                        to="catalog.industrytemplatecategoryattributemapping",
                        verbose_name="نگاشت مبدأ در قالب صنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "طرح ویژگی دسته\u200cبندی",
                "verbose_name_plural": "طرح\u200cهای ویژگی دسته\u200cبندی",
                "ordering": ["group_order", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="IndustryTemplateRecommendedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "template_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_for_categories",
                        to="catalog.industrytemplateattribute",
                        verbose_name="ویژگی قالب",
                    ),
                ),
                (
                    "template_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_options",
                        to="catalog.industrytemplatecategory",
                        verbose_name="دسته\u200cبندی قالب",
                    ),
                ),
            ],
            options={
                "verbose_name": "محور تنوع پیشنهادی قالب صنف",
                "verbose_name_plural": "محورهای تنوع پیشنهادی قالب صنف",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="StoreIndustryInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "installed_version",
                    models.PositiveIntegerField(
                        verbose_name="نسخه\u200cی نصب\u200cشده"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "نصب\u200cشده"), ("failed", "ناموفق")],
                        default="completed",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "categories_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد دسته\u200cبندی ساخته\u200cشده"
                    ),
                ),
                (
                    "attributes_created",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد ویژگی ساخته\u200cشده"
                    ),
                ),
                (
                    "industry_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="installations",
                        to="catalog.industrytemplate",
                        verbose_name="قالب صنف",
                    ),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_installation",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "نصب قالب صنف",
                "verbose_name_plural": "نصب\u200cهای قالب صنف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CategoryRecommendedOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_for_categories",
                        to="catalog.attribute",
                        verbose_name="ویژگی",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_options",
                        to="catalog.category",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "محور تنوع پیشنهادی دسته\u200cبندی",
                "verbose_name_plural": "محورهای تنوع پیشنهادی دسته\u200cبندی",
                "ordering": ["display_order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "attribute"),
                        name="uniq_category_recommended_option",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="industrytemplateattribute",
            constraint=models.UniqueConstraint(
                fields=("industry_template", "code"),
                name="uniq_template_attribute_code_per_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="industrytemplatecategory",
            constraint=models.UniqueConstraint(
                fields=("industry_template", "code"),
                name="uniq_template_category_code_per_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="industrytemplatecategoryattributemapping",
            constraint=models.UniqueConstraint(
                fields=("template_category", "template_attribute"),
                name="uniq_template_category_attribute",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryattributeschema",
            constraint=models.UniqueConstraint(
                fields=("category", "attribute"), name="uniq_category_attribute_schema"
            ),
        ),
        migrations.AddConstraint(
            model_name="industrytemplaterecommendedoption",
            constraint=models.UniqueConstraint(
                fields=("template_category", "template_attribute"),
                name="uniq_template_recommended_option",
            ),
        ),
    ]
