# Generated by Django 5.2.16 on 2026-07-29 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_industry_templates_and_category_schema"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="source_template_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="installed_values",
                to="catalog.industrytemplateattributevalue",
                verbose_name="مقدار مبدأ در قالب صنف",
            ),
        ),
        migrations.AddField(
            model_name="industrytemplate",
            name="content_fingerprint",
            field=models.CharField(
                blank=True,
                default="",
                help_text="هش SHA-256 قطعی محتوای قالب — نگاه کنید به ADR-27",
                max_length=64,
                verbose_name="اثرانگشت محتوا",
            ),
        ),
        migrations.AddField(
            model_name="industrytemplate",
            name="readiness",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("validation_failed", "اعتبارسنجی ناموفق"),
                    ("review_required", "نیازمند بازبینی"),
                    ("production_ready", "آماده\u200cی تولید"),
                    ("deprecated", "منسوخ"),
                    ("archived", "بایگانی\u200cشده"),
                ],
                default="draft",
                max_length=20,
                verbose_name="آمادگی",
            ),
        ),
        migrations.CreateModel(
            name="IndustryTemplateValidationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        max_length=64, verbose_name="اثرانگشت زمانِ اعتبارسنجی"
                    ),
                ),
                (
                    "validator_version",
                    models.CharField(
                        max_length=20, verbose_name="نسخه\u200cی اعتبارسنج"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("valid", "معتبر"), ("invalid", "نامعتبر")],
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "quality_score",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="امتیاز کیفیت"
                    ),
                ),
                (
                    "errors",
                    models.JSONField(blank=True, default=list, verbose_name="خطاها"),
                ),
                (
                    "warnings",
                    models.JSONField(blank=True, default=list, verbose_name="هشدارها"),
                ),
                (
                    "infos",
                    models.JSONField(blank=True, default=list, verbose_name="اطلاعات"),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="سنجه\u200cها"
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت اجرا (میلی\u200cثانیه)"
                    ),
                ),
                (
                    "industry_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_result",
                        to="catalog.industrytemplate",
                        verbose_name="قالب صنف",
                    ),
                ),
            ],
            options={
                "verbose_name": "نتیجه\u200cی اعتبارسنجی قالب صنف",
                "verbose_name_plural": "نتایج اعتبارسنجی قالب صنف",
            },
        ),
        migrations.CreateModel(
            name="StoreTemplateUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در حال انجام"),
                            ("completed", "تکمیل\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="کلید یکتایی درخواست"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان شروع"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان"
                    ),
                ),
                (
                    "selected_change_ids",
                    models.JSONField(
                        blank=True, default=list, verbose_name="تغییرات انتخاب\u200cشده"
                    ),
                ),
                (
                    "applied_changes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="تغییرات اعمال\u200cشده"
                    ),
                ),
                (
                    "skipped_changes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="تغییرات نادیده\u200cگرفته\u200cشده",
                    ),
                ),
                (
                    "conflicts",
                    models.JSONField(
                        blank=True, default=list, verbose_name="تعارض\u200cها"
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(blank=True, default="", verbose_name="دلیل شکست"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "from_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates_from",
                        to="catalog.industrytemplate",
                        verbose_name="قالب مبدأ",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_attempts",
                        to="catalog.storeindustryinstallation",
                        verbose_name="نصب",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_updates",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "target_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="updates_to",
                        to="catalog.industrytemplate",
                        verbose_name="قالب مقصد",
                    ),
                ),
            ],
            options={
                "verbose_name": "به\u200cروزرسانی نصب قالب صنف",
                "verbose_name_plural": "به\u200cروزرسانی\u200cهای نصب قالب صنف",
                "ordering": ["-started_at"],
            },
        ),
    ]
