# Generated by Django 5.2.16 on 2026-07-29 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_attributevalue_source_template_value_and_more"),
        ("orders", "0006_payment_gateway_config_and_attempt"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("order_placed", "ثبت سفارش (کاهش موجودی)"),
                            ("order_canceled", "لغو سفارش (بازگشت موجودی)"),
                            ("manual_adjustment", "اصلاح دستی موجودی"),
                        ],
                        max_length=20,
                        verbose_name="علت",
                    ),
                ),
                (
                    "delta",
                    models.IntegerField(
                        verbose_name="مقدار تغییر (مثبت=افزایش، منفی=کاهش)"
                    ),
                ),
                (
                    "stock_before",
                    models.IntegerField(verbose_name="موجودی پیش از تغییر"),
                ),
                ("stock_after", models.IntegerField(verbose_name="موجودی پس از تغییر")),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="یادداشت"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.productvariant",
                        verbose_name="تنوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد موجودی",
                "verbose_name_plural": "دفتر موجودی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "product", "-created_at"],
                        name="idx_stockmv_store_product",
                    )
                ],
            },
        ),
    ]
