# Generated by Django 5.2.16 on 2026-07-29 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_stockmovement"),
        ("orders", "0007_refund_refunditem_returnrequest_returnitem_and_more"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="return_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="orders.returnitem",
                verbose_name="قلمِ مرجوعی",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("order_placed", "ثبت سفارش (کاهش موجودی)"),
                    ("order_canceled", "لغو سفارش (بازگشت موجودی)"),
                    ("manual_adjustment", "اصلاح دستی موجودی"),
                    ("return_restock", "بازگشتِ مرجوعی به موجودی"),
                ],
                max_length=20,
                verbose_name="علت",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("return_item__isnull", False)),
                fields=("return_item",),
                name="uniq_stockmv_per_return_item",
            ),
        ),
    ]
