# Generated by Django 5.2.16 on 2026-07-29 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0015_stockmovement_return_item_alter_stockmovement_reason_and_more",
        ),
        ("orders", "0007_refund_refunditem_returnrequest_returnitem_and_more"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="refund_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="orders.refunditem",
                verbose_name="قلمِ استرداد",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("order_placed", "ثبت سفارش (کاهش موجودی)"),
                    ("order_canceled", "لغو سفارش (بازگشت موجودی)"),
                    ("manual_adjustment", "اصلاح دستی موجودی"),
                    ("return_restock", "بازگشتِ مرجوعی به موجودی"),
                    (
                        "refund_restock",
                        "بازگشتِ موجودی هنگام استرداد (بدون مرجوعیِ رسمی)",
                    ),
                ],
                max_length=20,
                verbose_name="علت",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("refund_item__isnull", False)),
                fields=("refund_item",),
                name="uniq_stockmv_per_refund_item",
            ),
        ),
    ]
