# Generated by Django 5.2.16 on 2026-07-29 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_coupon_store_enforce_not_null"),
        (
            "catalog",
            "0016_stockmovement_refund_item_alter_stockmovement_reason_and_more",
        ),
        ("orders", "0007_refund_refunditem_returnrequest_returnitem_and_more"),
        ("stores", "0005_store_admin_subdomain_enforce_not_null"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("order_placed", "ثبت سفارش (کاهش موجودی)"),
                    ("order_canceled", "لغو سفارش (بازگشت موجودی)"),
                    ("manual_adjustment", "اصلاح دستی موجودی"),
                    ("return_restock", "بازگشتِ مرجوعی به موجودی"),
                    (
                        "refund_restock",
                        "بازگشتِ موجودی هنگام استرداد (بدون مرجوعیِ رسمی)",
                    ),
                    (
                        "warehouse_transfer_out",
                        "خروج به\u200cواسطه\u200cی انتقال بین انبارها",
                    ),
                    (
                        "warehouse_transfer_in",
                        "ورود به\u200cواسطه\u200cی انتقال بین انبارها",
                    ),
                ],
                max_length=30,
                verbose_name="علت",
            ),
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام انبار")),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=40, verbose_name="کد انبار"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="آدرس"),
                ),
                (
                    "province",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="استان"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="شهر"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="کد پستی"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, default="", max_length=150, verbose_name="نام مسئول"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="تلفن مسئول"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="انبار پیش\u200cفرض"
                    ),
                ),
                (
                    "is_pickup_location",
                    models.BooleanField(
                        default=False, verbose_name="محلِ تحویلِ حضوری"
                    ),
                ),
                (
                    "fulfillment_priority",
                    models.PositiveIntegerField(
                        default=0, verbose_name="اولویتِ تأمین"
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouses",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "انبار",
                "verbose_name_plural": "انبارها",
                "ordering": ["fulfillment_priority", "name"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movements",
                to="catalog.warehouse",
                verbose_name="انبار",
            ),
        ),
        migrations.CreateModel(
            name="WarehouseInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "on_hand",
                    models.IntegerField(default=0, verbose_name="موجودیِ فیزیکی"),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="آستانه\u200cی هشدار کمبود"
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(default=True, verbose_name="پیگیری موجودی"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_balances",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_inventories",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_balances",
                        to="catalog.productvariant",
                        verbose_name="تنوع",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_balances",
                        to="catalog.warehouse",
                        verbose_name="انبار",
                    ),
                ),
            ],
            options={
                "verbose_name": "موجودیِ انبار",
                "verbose_name_plural": "موجودی\u200cهای انبار",
                "ordering": ["warehouse", "product"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "transfer_number",
                    models.CharField(max_length=24, verbose_name="شماره انتقال"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("requested", "درخواست\u200cشده"),
                            ("in_transit", "در حال ارسال"),
                            ("received", "دریافت\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "note",
                    models.TextField(blank=True, default="", verbose_name="یادداشت"),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دریافت"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان لغو"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warehouse_transfers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "destination_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="catalog.warehouse",
                        verbose_name="انبارِ مقصد",
                    ),
                ),
                (
                    "source_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="catalog.warehouse",
                        verbose_name="انبارِ مبدأ",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_transfers",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "انتقالِ انبار",
                "verbose_name_plural": "انتقال\u200cهای انبار",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WarehouseTransferItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "quantity_requested",
                    models.PositiveIntegerField(verbose_name="تعداد درخواستی"),
                ),
                (
                    "quantity_shipped",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد ارسالی"
                    ),
                ),
                (
                    "quantity_received",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد دریافتی"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.warehousetransfer",
                        verbose_name="انتقال",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_items",
                        to="catalog.productvariant",
                        verbose_name="تنوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلمِ انتقال",
                "verbose_name_plural": "اقلامِ انتقال",
            },
        ),
        migrations.CreateModel(
            name="InventoryReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="تعداد")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "فعال"),
                            ("consumed", "مصرف\u200cشده"),
                            ("released", "آزادشده"),
                            ("expired", "منقضی\u200cشده"),
                            ("cancelled", "لغوشده"),
                        ],
                        default="active",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="کلید یکتای درخواست",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="checkout",
                        max_length=30,
                        verbose_name="منبع",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انقضا"
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان آزادسازی"
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان مصرف"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_reservations",
                        to="cart.cart",
                        verbose_name="سبد خرید",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_reservations",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_reservations",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="catalog.productvariant",
                        verbose_name="تنوع",
                    ),
                ),
            ],
            options={
                "verbose_name": "رزروِ موجودی",
                "verbose_name_plural": "رزروهای موجودی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["store", "status", "expires_at"],
                        name="idx_reservation_status_expiry",
                    ),
                    models.Index(
                        fields=["product", "variant", "status"],
                        name="idx_reservation_target_status",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="reservation_quantity_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("idempotency_key", ""), _negated=True),
                        fields=("idempotency_key",),
                        name="uniq_reservation_idempotency_key_when_set",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_warehouse_code_per_store"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("store",),
                name="uniq_default_warehouse_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouseinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", True)),
                fields=("warehouse", "product"),
                name="uniq_warehouse_product_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouseinventory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("variant__isnull", False)),
                fields=("warehouse", "variant"),
                name="uniq_warehouse_variant_balance",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouseinventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("on_hand__gte", 0)),
                name="warehouse_inventory_on_hand_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousetransfer",
            constraint=models.UniqueConstraint(
                fields=("store", "transfer_number"),
                name="uniq_transfer_number_per_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousetransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_warehouse", models.F("destination_warehouse")),
                    _negated=True,
                ),
                name="transfer_source_ne_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehousetransferitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_requested__gt", 0)),
                name="transfer_item_quantity_positive",
            ),
        ),
    ]
