# Generated by Django 5.2.16 on 2026-07-29 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_provision_default_warehouses"),
        ("orders", "0008_shippingraterule_shippingzone_taxclass_taxrate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tax_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="orders.taxclass",
                verbose_name="دسته\u200cی مالیاتی",
            ),
        ),
    ]
