# Generated by Django 5.2.16 on 2026-07-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_product_tax_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("order_placed", "ثبت سفارش (کاهش موجودی)"),
                    ("order_canceled", "لغو سفارش (بازگشت موجودی)"),
                    ("manual_adjustment", "اصلاح دستی موجودی"),
                    ("return_restock", "بازگشتِ مرجوعی به موجودی"),
                    (
                        "refund_restock",
                        "بازگشتِ موجودی هنگام استرداد (بدون مرجوعیِ رسمی)",
                    ),
                    (
                        "warehouse_transfer_out",
                        "خروج به\u200cواسطه\u200cی انتقال بین انبارها",
                    ),
                    (
                        "warehouse_transfer_in",
                        "ورود به\u200cواسطه\u200cی انتقال بین انبارها",
                    ),
                    ("import_adjustment", "اصلاح موجودی از طریق واردات (Import)"),
                ],
                max_length=30,
                verbose_name="علت",
            ),
        ),
    ]
