# Generated by Django 5.2.16 on 2026-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_stockmovement_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="توضیح کوتاه"
            ),
        ),
        migrations.AddField(
            model_name="brand",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="فعال"),
        ),
        migrations.AddField(
            model_name="brand",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="نام انگلیسی"
            ),
        ),
    ]
