# Generated by Django 5.2.16 on 2026-08-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_brand_description_brand_is_active_brand_name_en"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name": "برند",
                "verbose_name_plural": "برندها",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="country",
            field=models.CharField(blank=True, max_length=80, verbose_name="کشور"),
        ),
        migrations.AddField(
            model_name="brand",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
        ),
        migrations.AddField(
            model_name="brand",
            name="website",
            field=models.URLField(
                blank=True, max_length=300, verbose_name="وب\u200cسایت"
            ),
        ),
    ]
