# Generated by Django 5.2.16 on 2026-08-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_alter_brand_options_brand_country_brand_sort_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributevalue",
            name="swatch_image",
            field=models.ImageField(
                blank=True,
                help_text="برای نمایشِ نمونه\u200cی تصویری به\u200cجای/همراهِ رنگ — مثلاً بافتِ پارچه یا الگوی چوب.",
                null=True,
                upload_to="attributes/swatches/",
                verbose_name="تصویر نمونه (Swatch)",
            ),
        ),
    ]
