# Generated by Django 5.2.16 on 2026-08-01 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_attributevalue_swatch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="caption",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="توضیحِ کوتاه (کپشن)"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="is_360",
            field=models.BooleanField(
                default=False,
                verbose_name="بخشی از مجموعه\u200cی ۳۶۰ درجه (به\u200cزودی)",
            ),
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("youtube", "یوتیوب"), ("aparat", "آپارات")],
                        max_length=10,
                        verbose_name="سرویس",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="لینکِ ویدیو")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان (اختیاری)"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیوی کالا",
                "verbose_name_plural": "ویدیوهای کالا",
                "ordering": ["display_order", "id"],
            },
        ),
    ]
