# Generated by Django 5.2.16 on 2026-08-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_productimage_caption_productimage_is_360_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="is_image_driving",
            field=models.BooleanField(
                default=False, verbose_name="تصویرمحور (سوییچِ خودکارِ تصویر)"
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="option_value",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="catalog.productoptionvalue",
                verbose_name="مقدارِ ویژگیِ مرتبط",
            ),
        ),
    ]
