# Generated by Django 5.2.16 on 2026-08-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_attribute_is_image_driving_productimage_option_value"),
        ("orders", "0008_shippingraterule_shippingzone_taxclass_taxrate_and_more"),
        ("stores", "0016_store_integration_connection"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="قیمتِ مستقلِ این تنوع (تومان)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="tax_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_variants",
                to="orders.taxclass",
                verbose_name="دسته\u200cی مالیاتیِ اختصاصی",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="wholesale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                help_text="زیرساختِ آماده\u200cبرایِ\u200cآینده\u200cیِ فروشِ عمده — هنوز در محاسبه\u200cی قیمتِ مشتری استفاده نمی\u200cشود.",
                max_digits=12,
                null=True,
                verbose_name="قیمتِ عمده (تومان)",
            ),
        ),
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام")),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, max_length=60, verbose_name="کد"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_tags",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "برچسبِ کالا",
                "verbose_name_plural": "برچسب\u200cهای کالا",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="catalog.producttag",
                verbose_name="برچسب\u200cها",
            ),
        ),
        migrations.AddConstraint(
            model_name="producttag",
            constraint=models.UniqueConstraint(
                fields=("store", "code"), name="uniq_producttag_code_per_store"
            ),
        ),
    ]
