# Generated by Django 5.2.16 on 2026-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_productvariant_price_productvariant_tax_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="input_type",
            field=models.CharField(
                choices=[("text", "متن"), ("color", "رنگ"), ("number", "عدد")],
                default="text",
                max_length=10,
                verbose_name="نوعِ ورودیِ مقادیر",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sales_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی = بدونِ محدودیت. اگر پر باشد، مشتری نمی\u200cتواند در یک سفارش بیش از این تعداد از این تنوع بخرد.",
                null=True,
                verbose_name="محدودیتِ فروش (حداکثر تعداد در هر سفارش)",
            ),
        ),
    ]
