# Generated by Django 5.2.16 on 2026-08-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_productoption_input_type_productvariant_sales_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publish_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="زمانِ انتشارِ زمان\u200cبندی\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="visibility",
            field=models.CharField(
                blank=True,
                choices=[("public", "نمایش عمومی"), ("link", "فقط با لینک مستقیم")],
                default="public",
                max_length=10,
                verbose_name="نمایش",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="sales_limit_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی = بدونِ حداقل.",
                null=True,
                verbose_name="محدودیتِ فروش (حداقل تعداد در هر سفارش)",
            ),
        ),
    ]
