# Generated by Django 5.2.16 on 2026-08-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_product_publish_at_product_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrytemplate",
            name="sector",
            field=models.CharField(
                choices=[
                    ("retail", "خرده\u200cفروشی و پوشاک"),
                    ("digital", "دیجیتال و الکترونیک"),
                    ("food", "خوراک و نوشیدنی"),
                    ("home", "خانه و آشپزخانه"),
                    ("beauty", "سلامت و زیبایی"),
                    ("sport", "ورزش و سرگرمی"),
                    ("culture", "فرهنگ و آموزش"),
                    ("auto", "خودرو و ابزار"),
                    ("industry", "صنعتی و ساختمان"),
                    ("services", "خدمات و تخصصی"),
                    ("other", "سایر"),
                ],
                default="other",
                max_length=20,
                verbose_name="رسته",
            ),
        ),
    ]
