# Generated by Django 5.2.16 on 2026-08-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_industry_template_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="industrytemplate",
            name="default_section_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="فهرست ترتیب\u200cدارِ کلیدهای نوع بخش (سازنده\u200cی بصری صفحه فروشگاه) که چیدمان پیشنهادیِ این صنف را می\u200cسازند. اعتبارسنجیِ این کلیدها در برابر Section Registry در لایه\u200cی apps.storefront_builder انجام می\u200cشود، نه اینجا، تا apps.catalog به آن اپ وابسته نشود.",
                verbose_name="بخش\u200cهای پیشنهادی صفحه اصلی",
            ),
        ),
    ]
