# Generated by Django 5.2.16 on 2026-08-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_industrytemplate_default_section_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="country_of_origin",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="کشور سازنده"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="model_code",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="مدل یا کد فنی"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "عدد"),
                    ("pack", "بسته"),
                    ("pair", "جفت"),
                    ("set", "ست"),
                    ("meter", "متر"),
                    ("sqm", "مترمربع"),
                    ("liter", "لیتر"),
                    ("ml", "میلی\u200cلیتر"),
                    ("gram", "گرم"),
                    ("kg", "کیلوگرم"),
                    ("strand", "شاخه"),
                    ("roll", "رول"),
                ],
                default="piece",
                max_length=12,
                verbose_name="واحد شمارش",
            ),
        ),
    ]
