# Generated by Django 5.2.16 on 2026-08-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0031_product_country_of_origin_product_model_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttag",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("general", "برچسبِ عادی"),
                    ("collection", "مجموعه\u200cی فروش (گروهِ دوم)"),
                ],
                default="general",
                max_length=12,
                verbose_name="کاربرد",
            ),
        ),
    ]
