# Generated by Django 5.2.17 on 2026-08-05 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_producttag_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="draft_created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="سازنده\u200cی پیش\u200cنویس",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_draft_placeholder",
            field=models.BooleanField(
                db_index=True,
                default=False,
                verbose_name="پیش\u200cنویسِ داخلیِ در حالِ ساخت",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="catalog.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
    ]
