# Generated by Django 5.2.17 on 2026-08-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0033_product_draft_placeholder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvideo",
            name="provider",
            field=models.CharField(
                choices=[
                    ("youtube", "یوتیوب"),
                    ("aparat", "آپارات"),
                    ("instagram", "اینستاگرام"),
                ],
                max_length=10,
                verbose_name="سرویس",
            ),
        ),
    ]
