# Generated by Django 5.2.17 on 2026-08-06 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0034_alter_productvideo_provider_add_instagram"),
        ("stores", "0017_platform_owner_admin_gap_fill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, max_length=170, verbose_name="اسلاگ"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="collections/images/",
                        verbose_name="تصویر",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "collection_type",
                    models.CharField(
                        choices=[("manual", "دستی"), ("smart", "هوشمند")],
                        default="manual",
                        max_length=10,
                        verbose_name="نوع کالکشن",
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True, default="", max_length=70, verbose_name="عنوان سئو"
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="توضیحات متا",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجادکننده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_collections",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آخرین ویرایشگر",
                    ),
                ),
            ],
            options={
                "verbose_name": "کالکشن",
                "verbose_name_plural": "کالکشن\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MerchantCollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.merchantcollection",
                        verbose_name="کالکشن",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="catalog.product",
                        verbose_name="کالا",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلمِ کالکشن",
                "verbose_name_plural": "اقلامِ کالکشن",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="merchantcollection",
            index=models.Index(
                fields=["store", "is_active"], name="idx_collection_store_active"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantcollection",
            index=models.Index(
                fields=["store", "name"], name="idx_collection_store_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantcollection",
            constraint=models.UniqueConstraint(
                fields=("store", "slug"), name="uniq_merchantcollection_slug_per_store"
            ),
        ),
        migrations.AddIndex(
            model_name="merchantcollectionitem",
            index=models.Index(
                fields=["collection", "order"], name="idx_mci_collection_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="merchantcollectionitem",
            constraint=models.UniqueConstraint(
                fields=("collection", "product"),
                name="uniq_collectionitem_product_per_collection",
            ),
        ),
    ]
