# Generated by Django 5.2.17 on 2026-08-06 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0035_merchantcollection_merchantcollectionitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchantcollection",
            name="source_legacy_product_tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_collections",
                to="catalog.producttag",
                verbose_name="برچسبِ «گروه دوم» مبدأ",
            ),
        ),
    ]
