"""صنایع خودرو و ابزارآلات (Phase 1F): قطعات خودرو، قطعات موتورسیکلت، ابزار و برق/روشنایی."""

INDUSTRY_TEMPLATES = [
    {
        "slug": "automotive-parts", "name": "لوازم یدکی خودرو", "icon": "🚗", "version": 1, "display_order": 21,
        "description": "دسته‌بندی و ویژگی‌های استاندارد برای فروشگاه‌های لوازم یدکی و اکسسوری خودرو.",
        "categories": [
            {"code": "auto-engine-parts", "name": "قطعات موتوری", "icon": "🔧"},
            {"code": "auto-body-parts", "name": "قطعات بدنه", "icon": "🚙"},
            {"code": "auto-electrical", "name": "قطعات برقی خودرو", "icon": "🔋"},
            {"code": "auto-accessories", "name": "لوازم جانبی خودرو", "icon": "🧰"},
            {"code": "auto-tires-wheels", "name": "لاستیک و رینگ", "icon": "🛞"},
        ],
        "attributes": [
            {"code": "auto-part-brand", "label": "برند سازنده", "data_type": "text"},
            {"code": "compatible-vehicle", "label": "خودروی سازگار", "data_type": "text"},
            {"code": "auto-part-condition", "label": "وضعیت قطعه", "data_type": "select", "display_type": "dropdown",
             "values": ["نو", "تعویضی سالم", "اصلی", "تولید داخل"]},
            {"code": "auto-warranty", "label": "گارانتی", "data_type": "text"},
            {"code": "auto-part-material", "label": "جنس", "data_type": "select", "display_type": "dropdown",
             "values": ["فلزی", "پلاستیکی", "کامپوزیت", "لاستیکی"]},
            {"code": "tire-size", "label": "سایز لاستیک", "data_type": "select", "display_type": "dropdown",
             "is_variant_axis": True, "values": ["185/65R15", "195/65R15", "205/55R16", "215/55R17", "225/45R18"]},
        ],
        "mappings": [
            {"category": cat, "attribute": attr, "group": "مشخصات", "required": required, "filterable": filterable}
            for cat in ("auto-engine-parts", "auto-body-parts", "auto-electrical", "auto-tires-wheels")
            for attr, required, filterable in [
                ("auto-part-brand", False, True), ("compatible-vehicle", True, True),
                ("auto-part-condition", True, True), ("auto-warranty", False, False),
            ]
        ] + [
            {"category": "auto-accessories", "attribute": "auto-part-brand", "group": "مشخصات", "filterable": True},
            {"category": "auto-accessories", "attribute": "auto-part-material", "group": "مشخصات",
             "filterable": True},
        ],
        "recommended_options": [
            {"category": "auto-tires-wheels", "attribute": "tire-size"},
        ],
    },
    {
        "slug": "motorcycle-parts", "name": "لوازم یدکی موتورسیکلت", "icon": "🏍️", "version": 1, "display_order": 22,
        "description": "دسته‌بندی و ویژگی‌های استاندارد برای فروشگاه‌های لوازم یدکی و اکسسوری موتورسیکلت.",
        "categories": [
            {"code": "moto-engine-parts", "name": "قطعات موتوری", "icon": "🔧"},
            {"code": "moto-body-parts", "name": "قطعات بدنه", "icon": "🏍️"},
            {"code": "moto-riding-gear", "name": "تجهیزات ایمنی راکب", "icon": "🪖"},
            {"code": "moto-accessories", "name": "لوازم جانبی موتور", "icon": "🧰"},
        ],
        "attributes": [
            {"code": "moto-part-brand", "label": "برند سازنده", "data_type": "text"},
            {"code": "compatible-moto-model", "label": "مدل موتور سازگار", "data_type": "text"},
            {"code": "moto-part-condition", "label": "وضعیت قطعه", "data_type": "select", "display_type": "dropdown",
             "values": ["نو", "تعویضی سالم", "اصلی"]},
            {"code": "helmet-standard", "label": "استاندارد کلاه ایمنی", "data_type": "text"},
            {"code": "moto-gear-material", "label": "جنس", "data_type": "select", "display_type": "dropdown",
             "values": ["چرم", "کوردورا", "کامپوزیت", "فلزی"]},
            {"code": "moto-gear-size", "label": "سایز تجهیزات", "data_type": "select", "display_type": "dropdown",
             "is_variant_axis": True, "values": ["S", "M", "L", "XL", "XXL"]},
        ],
        "mappings": [
            {"category": "moto-engine-parts", "attribute": "moto-part-brand", "group": "مشخصات",
             "filterable": True},
            {"category": "moto-engine-parts", "attribute": "compatible-moto-model", "group": "مشخصات",
             "required": True, "filterable": True},
            {"category": "moto-engine-parts", "attribute": "moto-part-condition", "group": "مشخصات",
             "required": True, "filterable": True},
            {"category": "moto-body-parts", "attribute": "compatible-moto-model", "group": "مشخصات",
             "required": True, "filterable": True},
            {"category": "moto-riding-gear", "attribute": "helmet-standard", "group": "ایمنی"},
            {"category": "moto-riding-gear", "attribute": "moto-gear-material", "group": "مشخصات",
             "filterable": True},
            {"category": "moto-accessories", "attribute": "moto-part-brand", "group": "مشخصات"},
        ],
        "recommended_options": [
            {"category": "moto-riding-gear", "attribute": "moto-gear-size"},
        ],
    },
    {
        "slug": "tools-hardware", "name": "ابزارآلات", "icon": "🛠️", "version": 1, "display_order": 23,
        "description": "دسته‌بندی و ویژگی‌های استاندارد برای فروشگاه‌های ابزارآلات و یراق‌آلات.",
        "categories": [
            {"code": "tools-power", "name": "ابزار برقی", "icon": "🔌"},
            {"code": "tools-hand", "name": "ابزار دستی", "icon": "🔨"},
            {"code": "tools-measuring", "name": "ابزار اندازه‌گیری", "icon": "📏"},
            {"code": "tools-fasteners", "name": "پیچ و مهره و یراق", "icon": "🔩"},
            {"code": "tools-safety", "name": "لوازم ایمنی کار", "icon": "🦺"},
        ],
        "attributes": [
            {"code": "tool-brand", "label": "برند", "data_type": "text"},
            {"code": "power-source", "label": "منبع تغذیه", "data_type": "select", "display_type": "dropdown",
             "values": ["برقی (سیم‌دار)", "باتری‌خور", "بادی", "دستی"]},
            {"code": "tool-power-watt", "label": "توان", "data_type": "number", "unit": "وات"},
            {"code": "tool-material", "label": "جنس", "data_type": "select", "display_type": "dropdown",
             "values": ["فولاد ضدزنگ", "فولاد کروم وانادیوم", "پلاستیک صنعتی", "آلومینیوم"]},
            {"code": "tool-warranty", "label": "گارانتی", "data_type": "text"},
            {"code": "tool-case-included", "label": "همراه با کیف/جعبه", "data_type": "boolean"},
        ],
        "mappings": [
            {"category": "tools-power", "attribute": "tool-brand", "group": "مشخصات", "required": True,
             "filterable": True},
            {"category": "tools-power", "attribute": "power-source", "group": "مشخصات", "required": True,
             "filterable": True},
            {"category": "tools-power", "attribute": "tool-power-watt", "group": "مشخصات فنی"},
            {"category": "tools-power", "attribute": "tool-warranty", "group": "خدمات پس از فروش"},
            {"category": "tools-hand", "attribute": "tool-brand", "group": "مشخصات", "filterable": True},
            {"category": "tools-hand", "attribute": "tool-material", "group": "مشخصات", "filterable": True},
            {"category": "tools-measuring", "attribute": "tool-brand", "group": "مشخصات", "filterable": True},
            {"category": "tools-fasteners", "attribute": "tool-material", "group": "مشخصات", "filterable": True},
            {"category": "tools-safety", "attribute": "tool-brand", "group": "مشخصات"},
            {"category": "tools-safety", "attribute": "tool-case-included", "group": "مشخصات"},
        ],
        "recommended_options": [],
    },
    {
        "slug": "electrical-lighting", "name": "برق و روشنایی", "icon": "💡", "version": 1, "display_order": 24,
        "description": "دسته‌بندی و ویژگی‌های استاندارد برای فروشگاه‌های تجهیزات برقی و روشنایی.",
        "categories": [
            {"code": "lighting-indoor", "name": "روشنایی داخلی", "icon": "💡"},
            {"code": "lighting-outdoor", "name": "روشنایی محوطه", "icon": "🔦"},
            {"code": "electrical-wiring", "name": "سیم و کابل", "icon": "🔌"},
            {"code": "electrical-switches", "name": "کلید و پریز", "icon": "🔘"},
            {"code": "electrical-smart", "name": "روشنایی و برق هوشمند", "icon": "📲"},
        ],
        "attributes": [
            {"code": "electrical-brand", "label": "برند", "data_type": "text"},
            {"code": "bulb-type", "label": "نوع لامپ", "data_type": "select", "display_type": "dropdown",
             "values": ["LED", "هالوژن", "کم‌مصرف", "رشته‌ای"]},
            {"code": "light-color-temp", "label": "دمای رنگ نور", "data_type": "select", "display_type": "dropdown",
             "values": ["مهتابی (۶۵۰۰K)", "آفتابی (۴۰۰۰K)", "زرد گرم (۲۷۰۰K)"]},
            {"code": "wattage", "label": "توان مصرفی", "data_type": "number", "unit": "وات"},
            {"code": "ip-rating", "label": "درجه حفاظت IP", "data_type": "select", "display_type": "dropdown",
             "values": ["IP20", "IP44", "IP65", "IP67"]},
            {"code": "smart-compatible", "label": "سازگار با خانه هوشمند", "data_type": "boolean"},
            {"code": "light-fixture-color", "label": "رنگ بدنه", "data_type": "color", "display_type": "swatch",
             "is_variant_axis": True,
             "values": [("مشکی", "#111827"), ("سفید", "#f9fafb"), ("طلایی", "#d4af37"), ("نقره‌ای", "#9ca3af")]},
        ],
        "mappings": [
            {"category": "lighting-indoor", "attribute": "electrical-brand", "group": "مشخصات", "filterable": True},
            {"category": "lighting-indoor", "attribute": "bulb-type", "group": "مشخصات", "required": True,
             "filterable": True},
            {"category": "lighting-indoor", "attribute": "light-color-temp", "group": "مشخصات", "filterable": True},
            {"category": "lighting-indoor", "attribute": "wattage", "group": "مشخصات فنی"},
            {"category": "lighting-outdoor", "attribute": "bulb-type", "group": "مشخصات", "filterable": True},
            {"category": "lighting-outdoor", "attribute": "ip-rating", "group": "مشخصات", "required": True,
             "filterable": True},
            {"category": "electrical-wiring", "attribute": "electrical-brand", "group": "مشخصات",
             "filterable": True},
            {"category": "electrical-switches", "attribute": "electrical-brand", "group": "مشخصات",
             "filterable": True},
            {"category": "electrical-smart", "attribute": "smart-compatible", "group": "مشخصات", "required": True,
             "filterable": True},
            {"category": "electrical-smart", "attribute": "electrical-brand", "group": "مشخصات",
             "filterable": True},
        ],
        "recommended_options": [
            {"category": "lighting-indoor", "attribute": "light-fixture-color"},
            {"category": "lighting-outdoor", "attribute": "light-fixture-color"},
        ],
    },
]
