# Generated by Django 5.2.16 on 2026-07-31 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0015_storeownershiptransfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "درون\u200cبرنامه\u200cای"),
                            ("sms", "پیامک"),
                            ("email", "ایمیل"),
                        ],
                        max_length=10,
                        verbose_name="کانال",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        verbose_name="موبایلِ گیرنده",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="ایمیلِ گیرنده",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="موضوع"
                    ),
                ),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "is_security",
                    models.BooleanField(
                        default=False,
                        verbose_name="اعلانِ امنیتی (غیرِقابلِ\u200cغیرفعال\u200cسازی)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظارِ ارسال"),
                            ("sent", "ارسال\u200cشده"),
                            ("failed", "ناموفق"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "attempts",
                    models.PositiveIntegerField(default=0, verbose_name="تعدادِ تلاش"),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="آخرین خطا"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ ارسال"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمانِ خوانده\u200cشدن"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="فراداده"),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="گیرنده",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="stores.store",
                        verbose_name="فروشگاه",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_user", "channel", "-created_at"],
                        name="idx_notif_user_channel",
                    ),
                    models.Index(
                        fields=["status", "channel"], name="idx_notif_status_channel"
                    ),
                ],
            },
        ),
    ]
